//
//  Created by nahive on 12/20/2016.
//  Copyright (c) 2016 nahive.io All rights reserved.
//

import UIKit

extension UIColor {
    convenience init(rgba: String) {
        var red:   CGFloat = 0.0
        var green: CGFloat = 0.0
        var blue:  CGFloat = 0.0
        var alpha: CGFloat = 1.0
        
        if rgba.hasPrefix("#") {
            let index   = rgba.index(rgba.startIndex, offsetBy: 1)
            let hex     = rgba.substring(from: index)
            let scanner = Scanner(string: hex)
            var hexValue: CUnsignedLongLong = 0
            if scanner.scanHexInt64(&hexValue) {
                switch (hex.characters.count) {
                case 3:
                    red   = CGFloat((hexValue & 0xF00) >> 8)       / 15.0
                    green = CGFloat((hexValue & 0x0F0) >> 4)       / 15.0
                    blue  = CGFloat(hexValue & 0x00F)              / 15.0
                case 4:
                    red   = CGFloat((hexValue & 0xF000) >> 12)     / 15.0
                    green = CGFloat((hexValue & 0x0F00) >> 8)      / 15.0
                    blue  = CGFloat((hexValue & 0x00F0) >> 4)      / 15.0
                    alpha = CGFloat(hexValue & 0x000F)             / 15.0
                case 6:
                    red   = CGFloat((hexValue & 0xFF0000) >> 16)   / 255.0
                    green = CGFloat((hexValue & 0x00FF00) >> 8)    / 255.0
                    blue  = CGFloat(hexValue & 0x0000FF)           / 255.0
                case 8:
                    red   = CGFloat((hexValue & 0xFF000000) >> 24) / 255.0
                    green = CGFloat((hexValue & 0x00FF0000) >> 16) / 255.0
                    blue  = CGFloat((hexValue & 0x0000FF00) >> 8)  / 255.0
                    alpha = CGFloat(hexValue & 0x000000FF)         / 255.0
                default:
                    print("Invalid RGB string, number of characters after # should be either 3, 4, 6 or 8")
                }
            } else {
                print("Scan hex error")
            }
        } else {
            print("Invalid RGB string, missing # as prefix")
        }
        self.init(red:red, green:green, blue:blue, alpha:alpha)
    }
}


extension UIColor {
    static var absoluteZero: UIColor { return UIColor(rgba: "#0048BA") } 
    static var acidGreen: UIColor { return UIColor(rgba: "#B0BF1A") } 
    static var aero: UIColor { return UIColor(rgba: "#7CB9E8") } 
    static var aeroBlue: UIColor { return UIColor(rgba: "#C9FFE5") } 
    static var africanViovar: UIColor { return UIColor(rgba: "#B284BE") } 
    static var airForceBlueRAF: UIColor { return UIColor(rgba: "#5D8AA8") } 
    static var airForceBlueUSAF: UIColor { return UIColor(rgba: "#00308F") } 
    static var airSuperiorityBlue: UIColor { return UIColor(rgba: "#72A0C1") } 
    static var alabamaCrimson: UIColor { return UIColor(rgba: "#AF002A") } 
    static var alabaster: UIColor { return UIColor(rgba: "#F2F0E6") } 
    static var aliceBlue: UIColor { return UIColor(rgba: "#F0F8FF") } 
    static var alienArmpit: UIColor { return UIColor(rgba: "#84DE02") } 
    static var alizarinCrimson: UIColor { return UIColor(rgba: "#E32636") } 
    static var alloyOrange: UIColor { return UIColor(rgba: "#C46210") } 
    static var almond: UIColor { return UIColor(rgba: "#EFDECD") } 
    static var amaranth: UIColor { return UIColor(rgba: "#E52B50") } 
    static var amaranthDeepPurple: UIColor { return UIColor(rgba: "#9F2B68") } 
    static var amaranthPink: UIColor { return UIColor(rgba: "#F19CBB") } 
    static var amaranthPurple: UIColor { return UIColor(rgba: "#AB274F") } 
    static var amaranthRed: UIColor { return UIColor(rgba: "#D3212D") } 
    static var amazon: UIColor { return UIColor(rgba: "#3B7A57") } 
    static var amazonite: UIColor { return UIColor(rgba: "#00C4B0") } 
    static var amber: UIColor { return UIColor(rgba: "#FFBF00") } 
    static var amberSAEECE: UIColor { return UIColor(rgba: "#FF7E00") } 
    static var americanRose: UIColor { return UIColor(rgba: "#FF033E") } 
    static var amethyst: UIColor { return UIColor(rgba: "#9966CC") } 
    static var androidGreen: UIColor { return UIColor(rgba: "#A4C639") } 
    static var antiFlashWhite: UIColor { return UIColor(rgba: "#F2F3F4") } 
    static var antiqueBrass: UIColor { return UIColor(rgba: "#CD9575") } 
    static var antiqueBronze: UIColor { return UIColor(rgba: "#665D1E") } 
    static var antiqueFuchsia: UIColor { return UIColor(rgba: "#915C83") } 
    static var antiqueRuby: UIColor { return UIColor(rgba: "#841B2D") } 
    static var antiqueWhite: UIColor { return UIColor(rgba: "#FAEBD7") } 
    static var aoEnglish: UIColor { return UIColor(rgba: "#008000") } 
    static var appleGreen: UIColor { return UIColor(rgba: "#8DB600") } 
    static var apricot: UIColor { return UIColor(rgba: "#FBCEB1") } 
    static var aqua: UIColor { return UIColor(rgba: "#00FFFF") } 
    static var aquamarine: UIColor { return UIColor(rgba: "#7FFFD4") } 
    static var arcticLime: UIColor { return UIColor(rgba: "#D0FF14") } 
    static var armyGreen: UIColor { return UIColor(rgba: "#4B5320") } 
    static var arsenic: UIColor { return UIColor(rgba: "#3B444B") } 
    static var artichoke: UIColor { return UIColor(rgba: "#8F9779") } 
    static var arylideYellow: UIColor { return UIColor(rgba: "#E9D66B") } 
    static var ashGrey: UIColor { return UIColor(rgba: "#B2BEB5") } 
    static var asparagus: UIColor { return UIColor(rgba: "#87A96B") } 
    static var atomicTangerine: UIColor { return UIColor(rgba: "#FF9966") } 
    static var auburn: UIColor { return UIColor(rgba: "#A52A2A") } 
    static var aureolin: UIColor { return UIColor(rgba: "#FDEE00") } 
    static var auroMetalSaurus: UIColor { return UIColor(rgba: "#6E7F80") } 
    static var avocado: UIColor { return UIColor(rgba: "#568203") } 
    static var awesome: UIColor { return UIColor(rgba: "#FF2052") } 
    static var aztecGold: UIColor { return UIColor(rgba: "#C39953") } 
    static var azure: UIColor { return UIColor(rgba: "#007FFF") } 
    static var azureWebColor: UIColor { return UIColor(rgba: "#F0FFFF") } 
    static var azureMist: UIColor { return UIColor(rgba: "#F0FFFF") } 
    static var azureishWhite: UIColor { return UIColor(rgba: "#DBE9F4") } 
    static var babyBlue: UIColor { return UIColor(rgba: "#89CFF0") } 
    static var babyBlueEyes: UIColor { return UIColor(rgba: "#A1CAF1") } 
    static var babyPink: UIColor { return UIColor(rgba: "#F4C2C2") } 
    static var babyPowder: UIColor { return UIColor(rgba: "#FEFEFA") } 
    static var bakerMillerPink: UIColor { return UIColor(rgba: "#FF91AF") } 
    static var ballBlue: UIColor { return UIColor(rgba: "#21ABCD") } 
    static var bananaMania: UIColor { return UIColor(rgba: "#FAE7B5") } 
    static var bananaYellow: UIColor { return UIColor(rgba: "#FFE135") } 
    static var bangladeshGreen: UIColor { return UIColor(rgba: "#006A4E") } 
    static var barbiePink: UIColor { return UIColor(rgba: "#E0218A") } 
    static var barnRed: UIColor { return UIColor(rgba: "#7C0A02") } 
    static var batteryChargedBlue: UIColor { return UIColor(rgba: "#1DACD6") } 
    static var battleshipGrey: UIColor { return UIColor(rgba: "#848482") } 
    static var bazaar: UIColor { return UIColor(rgba: "#98777B") } 
    static var beauBlue: UIColor { return UIColor(rgba: "#BCD4E6") } 
    static var beaver: UIColor { return UIColor(rgba: "#9F8170") } 
    static var begonia: UIColor { return UIColor(rgba: "#FA6E79") } 
    static var beige: UIColor { return UIColor(rgba: "#F5F5DC") } 
    static var bdazzledBlue: UIColor { return UIColor(rgba: "#2E5894") }
    static var bigDipOruby: UIColor { return UIColor(rgba: "#9C2542") }
    static var bigFootFeet: UIColor { return UIColor(rgba: "#E88E5A") } 
    static var bisque: UIColor { return UIColor(rgba: "#FFE4C4") } 
    static var bistre: UIColor { return UIColor(rgba: "#3D2B1F") } 
    static var bistreBrown: UIColor { return UIColor(rgba: "#967117") } 
    static var bitterLemon: UIColor { return UIColor(rgba: "#CAE00D") } 
    static var bitterLime: UIColor { return UIColor(rgba: "#BFFF00") } 
    static var bittersweet: UIColor { return UIColor(rgba: "#FE6F5E") } 
    static var bittersweetShimmer: UIColor { return UIColor(rgba: "#BF4F51") } 
    static var black: UIColor { return UIColor(rgba: "#000000") } 
    static var blackBean: UIColor { return UIColor(rgba: "#3D0C02") } 
    static var blackCoral: UIColor { return UIColor(rgba: "#54626F") } 
    static var blackLeatherJacket: UIColor { return UIColor(rgba: "#253529") } 
    static var blackOlive: UIColor { return UIColor(rgba: "#3B3C36") } 
    static var blackShadows: UIColor { return UIColor(rgba: "#BFAFB2") } 
    static var blanchedAlmond: UIColor { return UIColor(rgba: "#FFEBCD") } 
    static var blastOffBronze: UIColor { return UIColor(rgba: "#A57164") } 
    static var bleuDeFrance: UIColor { return UIColor(rgba: "#318CE7") } 
    static var blizzardBlue: UIColor { return UIColor(rgba: "#ACE5EE") } 
    static var blond: UIColor { return UIColor(rgba: "#FAF0BE") } 
    static var blue: UIColor { return UIColor(rgba: "#0000FF") } 
    static var blueCrayola: UIColor { return UIColor(rgba: "#1F75FE") } 
    static var blueMunsell: UIColor { return UIColor(rgba: "#0093AF") } 
    static var blueNCS: UIColor { return UIColor(rgba: "#0087BD") } 
    static var bluePantone: UIColor { return UIColor(rgba: "#0018A8") } 
    static var bluePigment: UIColor { return UIColor(rgba: "#333399") } 
    static var blueRYB: UIColor { return UIColor(rgba: "#0247FE") } 
    static var blueBell: UIColor { return UIColor(rgba: "#A2A2D0") } 
    static var blueBolt: UIColor { return UIColor(rgba: "#00B9FB") } 
    static var blueGray: UIColor { return UIColor(rgba: "#6699CC") } 
    static var blueGreen: UIColor { return UIColor(rgba: "#0D98BA") } 
    static var blueJeans: UIColor { return UIColor(rgba: "#5DADEC") } 
    static var blueLagoon: UIColor { return UIColor(rgba: "#ACE5EE") } 
    static var blueMagentaViovar: UIColor { return UIColor(rgba: "#553592") } 
    static var blueSapphire: UIColor { return UIColor(rgba: "#126180") } 
    static var blueViovar: UIColor { return UIColor(rgba: "#8A2BE2") } 
    static var blueYonder: UIColor { return UIColor(rgba: "#5072A7") } 
    static var blueberry: UIColor { return UIColor(rgba: "#4F86F7") } 
    static var bluebonnet: UIColor { return UIColor(rgba: "#1C1CF0") } 
    static var blush: UIColor { return UIColor(rgba: "#DE5D83") } 
    static var bole: UIColor { return UIColor(rgba: "#79443B") } 
    static var bondiBlue: UIColor { return UIColor(rgba: "#0095B6") } 
    static var bone: UIColor { return UIColor(rgba: "#E3DAC9") } 
    static var boogerBuster: UIColor { return UIColor(rgba: "#DDE26A") } 
    static var bostonUniversityRed: UIColor { return UIColor(rgba: "#CC0000") } 
    static var bottleGreen: UIColor { return UIColor(rgba: "#006A4E") } 
    static var boysenberry: UIColor { return UIColor(rgba: "#873260") } 
    static var brandeisBlue: UIColor { return UIColor(rgba: "#0070FF") } 
    static var brass: UIColor { return UIColor(rgba: "#B5A642") } 
    static var brickRed: UIColor { return UIColor(rgba: "#CB4154") } 
    static var brightCerulean: UIColor { return UIColor(rgba: "#1DACD6") } 
    static var brightGreen: UIColor { return UIColor(rgba: "#66FF00") } 
    static var brightLavender: UIColor { return UIColor(rgba: "#BF94E4") } 
    static var brightLilac: UIColor { return UIColor(rgba: "#D891EF") } 
    static var brightMaroon: UIColor { return UIColor(rgba: "#C32148") } 
    static var brightNavyBlue: UIColor { return UIColor(rgba: "#1974D2") } 
    static var brightPink: UIColor { return UIColor(rgba: "#FF007F") } 
    static var brightTurquoise: UIColor { return UIColor(rgba: "#08E8DE") } 
    static var brightUbe: UIColor { return UIColor(rgba: "#D19FE8") } 
    static var brightYellowCrayola: UIColor { return UIColor(rgba: "#FFAA1D") } 
    static var brilliantAzure: UIColor { return UIColor(rgba: "#3399FF") } 
    static var brilliantLavender: UIColor { return UIColor(rgba: "#F4BBFF") } 
    static var brilliantRose: UIColor { return UIColor(rgba: "#FF55A3") } 
    static var brinkPink: UIColor { return UIColor(rgba: "#FB607F") } 
    static var britishRacingGreen: UIColor { return UIColor(rgba: "#004225") } 
    static var bronze: UIColor { return UIColor(rgba: "#CD7F32") } 
    static var bronzeYellow: UIColor { return UIColor(rgba: "#737000") } 
    static var brownTraditional: UIColor { return UIColor(rgba: "#964B00") } 
    static var brownWeb: UIColor { return UIColor(rgba: "#A52A2A") } 
    static var brownNose: UIColor { return UIColor(rgba: "#6B4423") } 
    static var brownSugar: UIColor { return UIColor(rgba: "#AF6E4D") } 
    static var brownYellow: UIColor { return UIColor(rgba: "#cc9966") } 
    static var brunswickGreen: UIColor { return UIColor(rgba: "#1B4D3E") } 
    static var bubbleGum: UIColor { return UIColor(rgba: "#FFC1CC") } 
    static var bubbles: UIColor { return UIColor(rgba: "#E7FEFF") } 
    static var budGreen: UIColor { return UIColor(rgba: "#7BB661") } 
    static var buff: UIColor { return UIColor(rgba: "#F0DC82") } 
    static var bulgarianRose: UIColor { return UIColor(rgba: "#480607") } 
    static var burgundy: UIColor { return UIColor(rgba: "#800020") } 
    static var burlywood: UIColor { return UIColor(rgba: "#DEB887") } 
    static var burnishedBrown: UIColor { return UIColor(rgba: "#A17A74") } 
    static var burntOrange: UIColor { return UIColor(rgba: "#CC5500") } 
    static var burntSienna: UIColor { return UIColor(rgba: "#E97451") } 
    static var burntUmber: UIColor { return UIColor(rgba: "#8A3324") } 
    static var buttonBlue: UIColor { return UIColor(rgba: "#24A0ED") } 
    static var byzantine: UIColor { return UIColor(rgba: "#BD33A4") } 
    static var byzantium: UIColor { return UIColor(rgba: "#702963") } 
    static var cadet: UIColor { return UIColor(rgba: "#536872") } 
    static var cadetBlue: UIColor { return UIColor(rgba: "#5F9EA0") } 
    static var cadetGrey: UIColor { return UIColor(rgba: "#91A3B0") } 
    static var cadmiumGreen: UIColor { return UIColor(rgba: "#006B3C") } 
    static var cadmiumOrange: UIColor { return UIColor(rgba: "#ED872D") } 
    static var cadmiumRed: UIColor { return UIColor(rgba: "#E30022") } 
    static var cadmiumYellow: UIColor { return UIColor(rgba: "#FFF600") } 
    static var caféAuLait: UIColor { return UIColor(rgba: "#A67B5B") } 
    static var caféNoir: UIColor { return UIColor(rgba: "#4B3621") } 
    static var calPolyPomonaGreen: UIColor { return UIColor(rgba: "#1E4D2B") } 
    static var cambridgeBlue: UIColor { return UIColor(rgba: "#A3C1AD") } 
    static var camel: UIColor { return UIColor(rgba: "#C19A6B") } 
    static var cameoPink: UIColor { return UIColor(rgba: "#EFBBCC") } 
    static var camouflageGreen: UIColor { return UIColor(rgba: "#78866B") } 
    static var canary: UIColor { return UIColor(rgba: "#FFFF99") } 
    static var canaryYellow: UIColor { return UIColor(rgba: "#FFEF00") } 
    static var candyAppleRed: UIColor { return UIColor(rgba: "#FF0800") } 
    static var candyPink: UIColor { return UIColor(rgba: "#E4717A") } 
    static var capri: UIColor { return UIColor(rgba: "#00BFFF") } 
    static var caputMortuum: UIColor { return UIColor(rgba: "#592720") } 
    static var cardinal: UIColor { return UIColor(rgba: "#C41E3A") } 
    static var caribbeanGreen: UIColor { return UIColor(rgba: "#00CC99") } 
    static var carmine: UIColor { return UIColor(rgba: "#960018") } 
    static var carmineMP: UIColor { return UIColor(rgba: "#D70040") }
    static var carminePink: UIColor { return UIColor(rgba: "#EB4C42") } 
    static var carmineRed: UIColor { return UIColor(rgba: "#FF0038") } 
    static var carnationPink: UIColor { return UIColor(rgba: "#FFA6C9") } 
    static var carnelian: UIColor { return UIColor(rgba: "#B31B1B") } 
    static var carolinaBlue: UIColor { return UIColor(rgba: "#56A0D3") } 
    static var carrotOrange: UIColor { return UIColor(rgba: "#ED9121") } 
    static var castvaronGreen: UIColor { return UIColor(rgba: "#00563F") } 
    static var catalinaBlue: UIColor { return UIColor(rgba: "#062A78") } 
    static var catawba: UIColor { return UIColor(rgba: "#703642") } 
    static var cedarChest: UIColor { return UIColor(rgba: "#C95A49") } 
    static var ceil: UIColor { return UIColor(rgba: "#92A1CF") } 
    static var celadon: UIColor { return UIColor(rgba: "#ACE1AF") } 
    static var celadonBlue: UIColor { return UIColor(rgba: "#007BA7") } 
    static var celadonGreen: UIColor { return UIColor(rgba: "#2F847C") } 
    static var celeste: UIColor { return UIColor(rgba: "#B2FFFF") } 
    static var celestialBlue: UIColor { return UIColor(rgba: "#4997D0") } 
    static var cerise: UIColor { return UIColor(rgba: "#DE3163") } 
    static var cerisePink: UIColor { return UIColor(rgba: "#EC3B83") } 
    static var cerulean: UIColor { return UIColor(rgba: "#007BA7") } 
    static var ceruleanBlue: UIColor { return UIColor(rgba: "#2A52BE") } 
    static var ceruleanFrost: UIColor { return UIColor(rgba: "#6D9BC3") } 
    static var cGBlue: UIColor { return UIColor(rgba: "#007AA5") } 
    static var cGRed: UIColor { return UIColor(rgba: "#E03C31") } 
    static var chamoisee: UIColor { return UIColor(rgba: "#A0785A") } 
    static var champagne: UIColor { return UIColor(rgba: "#F7E7CE") } 
    static var champagnePink: UIColor { return UIColor(rgba: "#F1DDCF") } 
    static var charcoal: UIColor { return UIColor(rgba: "#36454F") } 
    static var charlestonGreen: UIColor { return UIColor(rgba: "#232B2B") } 
    static var charmPink: UIColor { return UIColor(rgba: "#E68FAC") } 
    static var chartreuseTraditional: UIColor { return UIColor(rgba: "#DFFF00") } 
    static var chartreuseWeb: UIColor { return UIColor(rgba: "#7FFF00") } 
    static var cherry: UIColor { return UIColor(rgba: "#DE3163") } 
    static var cherryBlossomPink: UIColor { return UIColor(rgba: "#FFB7C5") } 
    static var chestnut: UIColor { return UIColor(rgba: "#954535") } 
    static var chinaPink: UIColor { return UIColor(rgba: "#DE6FA1") } 
    static var chinaRose: UIColor { return UIColor(rgba: "#A8516E") } 
    static var chineseRed: UIColor { return UIColor(rgba: "#AA381E") } 
    static var chineseViovar: UIColor { return UIColor(rgba: "#856088") } 
    static var chlorophyllGreen: UIColor { return UIColor(rgba: "#4AFF00") } 
    static var chocolateTraditional: UIColor { return UIColor(rgba: "#7B3F00") } 
    static var chocolateWeb: UIColor { return UIColor(rgba: "#D2691E") } 
    static var chromeYellow: UIColor { return UIColor(rgba: "#FFA700") } 
    static var cinereous: UIColor { return UIColor(rgba: "#98817B") } 
    static var cinnabar: UIColor { return UIColor(rgba: "#E34234") } 
    static var cinnamon: UIColor { return UIColor(rgba: "#D2691E") }
    static var cinnamonSatin: UIColor { return UIColor(rgba: "#CD607E") } 
    static var citrine: UIColor { return UIColor(rgba: "#E4D00A") } 
    static var citron: UIColor { return UIColor(rgba: "#9FA91F") } 
    static var claret: UIColor { return UIColor(rgba: "#7F1734") } 
    static var classicRose: UIColor { return UIColor(rgba: "#FBCCE7") } 
    static var cobaltBlue: UIColor { return UIColor(rgba: "#0047AB") } 
    static var cocoaBrown: UIColor { return UIColor(rgba: "#D2691E") } 
    static var coconut: UIColor { return UIColor(rgba: "#965A3E") } 
    static var coffee: UIColor { return UIColor(rgba: "#6F4E37") } 
    static var columbiaBlue: UIColor { return UIColor(rgba: "#C4D8E2") } 
    static var congoPink: UIColor { return UIColor(rgba: "#F88379") } 
    static var coolBlack: UIColor { return UIColor(rgba: "#002E63") } 
    static var coolGrey: UIColor { return UIColor(rgba: "#8C92AC") } 
    static var copper: UIColor { return UIColor(rgba: "#B87333") } 
    static var copperCrayola: UIColor { return UIColor(rgba: "#DA8A67") } 
    static var copperPenny: UIColor { return UIColor(rgba: "#AD6F69") } 
    static var copperRed: UIColor { return UIColor(rgba: "#CB6D51") } 
    static var copperRose: UIColor { return UIColor(rgba: "#996666") } 
    static var coquelicot: UIColor { return UIColor(rgba: "#FF3800") } 
    static var coral: UIColor { return UIColor(rgba: "#FF7F50") } 
    static var coralPink: UIColor { return UIColor(rgba: "#F88379") } 
    static var coralRed: UIColor { return UIColor(rgba: "#FF4040") } 
    static var coralReef: UIColor { return UIColor(rgba: "#FD7C6E") } 
    static var cordovan: UIColor { return UIColor(rgba: "#893F45") } 
    static var corn: UIColor { return UIColor(rgba: "#FBEC5D") } 
    static var cornellRed: UIColor { return UIColor(rgba: "#B31B1B") } 
    static var cornflowerBlue: UIColor { return UIColor(rgba: "#6495ED") } 
    static var cornsilk: UIColor { return UIColor(rgba: "#FFF8DC") } 
    static var cosmicCobalt: UIColor { return UIColor(rgba: "#2E2D88") } 
    static var cosmicLatte: UIColor { return UIColor(rgba: "#FFF8E7") } 
    static var coyoteBrown: UIColor { return UIColor(rgba: "#81613C") } 
    static var cottonCandy: UIColor { return UIColor(rgba: "#FFBCD9") } 
    static var cream: UIColor { return UIColor(rgba: "#FFFDD0") } 
    static var crimson: UIColor { return UIColor(rgba: "#DC143C") } 
    static var crimsonGlory: UIColor { return UIColor(rgba: "#BE0032") } 
    static var crimsonRed: UIColor { return UIColor(rgba: "#990000") } 
    static var cultured: UIColor { return UIColor(rgba: "#F5F5F5") } 
    static var cyan: UIColor { return UIColor(rgba: "#00FFFF") } 
    static var cyanAzure: UIColor { return UIColor(rgba: "#4E82B4") } 
    static var cyanBlueAzure: UIColor { return UIColor(rgba: "#4682BF") } 
    static var cyanCobaltBlue: UIColor { return UIColor(rgba: "#28589C") } 
    static var cyanCornflowerBlue: UIColor { return UIColor(rgba: "#188BC2") } 
    static var cyanProcess: UIColor { return UIColor(rgba: "#00B7EB") } 
    static var cyberGrape: UIColor { return UIColor(rgba: "#58427C") } 
    static var cyberYellow: UIColor { return UIColor(rgba: "#FFD300") } 
    static var cyclamen: UIColor { return UIColor(rgba: "#F56FA1") } 
    static var daffodil: UIColor { return UIColor(rgba: "#FFFF31") } 
    static var dandelion: UIColor { return UIColor(rgba: "#F0E130") } 
    static var darkBlue: UIColor { return UIColor(rgba: "#00008B") } 
    static var darkBlueGray: UIColor { return UIColor(rgba: "#666699") } 
    static var darkBrown: UIColor { return UIColor(rgba: "#654321") } 
    static var darkBrownTangelo: UIColor { return UIColor(rgba: "#88654E") } 
    static var darkByzantium: UIColor { return UIColor(rgba: "#5D3954") } 
    static var darkCandyAppleRed: UIColor { return UIColor(rgba: "#A40000") } 
    static var darkCerulean: UIColor { return UIColor(rgba: "#08457E") } 
    static var darkChestnut: UIColor { return UIColor(rgba: "#986960") } 
    static var darkCoral: UIColor { return UIColor(rgba: "#CD5B45") } 
    static var darkCyan: UIColor { return UIColor(rgba: "#008B8B") } 
    static var darkElectricBlue: UIColor { return UIColor(rgba: "#536878") } 
    static var darkGoldenrod: UIColor { return UIColor(rgba: "#B8860B") } 
    static var darkGrayX11: UIColor { return UIColor(rgba: "#A9A9A9") } 
    static var darkGreen: UIColor { return UIColor(rgba: "#013220") } 
    static var darkGreenX11: UIColor { return UIColor(rgba: "#006400") } 
    static var darkGunmetal: UIColor { return UIColor(rgba: "#1F262A") } 
    static var darkImperialBlue: UIColor { return UIColor(rgba: "#00416A") }
    static var darkJungleGreen: UIColor { return UIColor(rgba: "#1A2421") } 
    static var darkKhaki: UIColor { return UIColor(rgba: "#BDB76B") } 
    static var darkLava: UIColor { return UIColor(rgba: "#483C32") } 
    static var darkLavender: UIColor { return UIColor(rgba: "#734F96") } 
    static var darkLiver: UIColor { return UIColor(rgba: "#534B4F") } 
    static var darkLiverHorses: UIColor { return UIColor(rgba: "#543D37") } 
    static var darkMagenta: UIColor { return UIColor(rgba: "#8B008B") } 
    static var darkMediumGray: UIColor { return UIColor(rgba: "#A9A9A9") } 
    static var darkMidnightBlue: UIColor { return UIColor(rgba: "#003366") } 
    static var darkMossGreen: UIColor { return UIColor(rgba: "#4A5D23") } 
    static var darkOliveGreen: UIColor { return UIColor(rgba: "#556B2F") } 
    static var darkOrange: UIColor { return UIColor(rgba: "#FF8C00") } 
    static var darkOrchid: UIColor { return UIColor(rgba: "#9932CC") } 
    static var darkPastelBlue: UIColor { return UIColor(rgba: "#779ECB") } 
    static var darkPastelGreen: UIColor { return UIColor(rgba: "#03C03C") } 
    static var darkPastelPurple: UIColor { return UIColor(rgba: "#966FD6") } 
    static var darkPastelRed: UIColor { return UIColor(rgba: "#C23B22") } 
    static var darkPink: UIColor { return UIColor(rgba: "#E75480") } 
    static var darkPowderBlue: UIColor { return UIColor(rgba: "#003399") } 
    static var darkPuce: UIColor { return UIColor(rgba: "#4F3A3C") } 
    static var darkPurple: UIColor { return UIColor(rgba: "#301934") } 
    static var darkRaspberry: UIColor { return UIColor(rgba: "#872657") } 
    static var darkRed: UIColor { return UIColor(rgba: "#8B0000") } 
    static var darkSalmon: UIColor { return UIColor(rgba: "#E9967A") } 
    static var darkScarvar: UIColor { return UIColor(rgba: "#560319") } 
    static var darkSeaGreen: UIColor { return UIColor(rgba: "#8FBC8F") } 
    static var darkSienna: UIColor { return UIColor(rgba: "#3C1414") } 
    static var darkSkyBlue: UIColor { return UIColor(rgba: "#8CBED6") } 
    static var darkSlateBlue: UIColor { return UIColor(rgba: "#483D8B") } 
    static var darkSlateGray: UIColor { return UIColor(rgba: "#2F4F4F") } 
    static var darkSpringGreen: UIColor { return UIColor(rgba: "#177245") } 
    static var darkTan: UIColor { return UIColor(rgba: "#918151") } 
    static var darkTangerine: UIColor { return UIColor(rgba: "#FFA812") } 
    static var darkTaupe: UIColor { return UIColor(rgba: "#483C32") } 
    static var darkTerraCotta: UIColor { return UIColor(rgba: "#CC4E5C") } 
    static var darkTurquoise: UIColor { return UIColor(rgba: "#00CED1") } 
    static var darkVanilla: UIColor { return UIColor(rgba: "#D1BEA8") } 
    static var darkViovar: UIColor { return UIColor(rgba: "#9400D3") } 
    static var darkYellow: UIColor { return UIColor(rgba: "#9B870C") } 
    static var dartmouthGreen: UIColor { return UIColor(rgba: "#00703C") } 
    static var davysGrey: UIColor { return UIColor(rgba: "#555555") }
    static var debianRed: UIColor { return UIColor(rgba: "#D70A53") } 
    static var deepAquamarine: UIColor { return UIColor(rgba: "#40826D") } 
    static var deepCarmine: UIColor { return UIColor(rgba: "#A9203E") } 
    static var deepCarminePink: UIColor { return UIColor(rgba: "#EF3038") } 
    static var deepCarrotOrange: UIColor { return UIColor(rgba: "#E9692C") } 
    static var deepCerise: UIColor { return UIColor(rgba: "#DA3287") } 
    static var deepChampagne: UIColor { return UIColor(rgba: "#FAD6A5") } 
    static var deepChestnut: UIColor { return UIColor(rgba: "#B94E48") } 
    static var deepCoffee: UIColor { return UIColor(rgba: "#704241") } 
    static var deepFuchsia: UIColor { return UIColor(rgba: "#C154C1") } 
    static var deepGreen: UIColor { return UIColor(rgba: "#056608") } 
    static var deepGreenCyanTurquoise: UIColor { return UIColor(rgba: "#0E7C61") } 
    static var deepJungleGreen: UIColor { return UIColor(rgba: "#004B49") } 
    static var deepKoamaru: UIColor { return UIColor(rgba: "#333366") } 
    static var deepLemon: UIColor { return UIColor(rgba: "#F5C71A") } 
    static var deepLilac: UIColor { return UIColor(rgba: "#9955BB") } 
    static var deepMagenta: UIColor { return UIColor(rgba: "#CC00CC") } 
    static var deepMaroon: UIColor { return UIColor(rgba: "#820000") } 
    static var deepMauve: UIColor { return UIColor(rgba: "#D473D4") } 
    static var deepMossGreen: UIColor { return UIColor(rgba: "#355E3B") } 
    static var deepPeach: UIColor { return UIColor(rgba: "#FFCBA4") } 
    static var deepPink: UIColor { return UIColor(rgba: "#FF1493") } 
    static var deepPuce: UIColor { return UIColor(rgba: "#A95C68") } 
    static var deepRed: UIColor { return UIColor(rgba: "#850101") } 
    static var deepRuby: UIColor { return UIColor(rgba: "#843F5B") } 
    static var deepSaffron: UIColor { return UIColor(rgba: "#FF9933") } 
    static var deepSkyBlue: UIColor { return UIColor(rgba: "#00BFFF") } 
    static var deepSpaceSparkle: UIColor { return UIColor(rgba: "#4A646C") } 
    static var deepSpringBud: UIColor { return UIColor(rgba: "#556B2F") } 
    static var deepTaupe: UIColor { return UIColor(rgba: "#7E5E60") } 
    static var deepTuscanRed: UIColor { return UIColor(rgba: "#66424D") } 
    static var deepViovar: UIColor { return UIColor(rgba: "#330066") } 
    static var deer: UIColor { return UIColor(rgba: "#BA8759") } 
    static var denim: UIColor { return UIColor(rgba: "#1560BD") } 
    static var denimBlue: UIColor { return UIColor(rgba: "#2243B6") } 
    static var desaturatedCyan: UIColor { return UIColor(rgba: "#669999") } 
    static var desert: UIColor { return UIColor(rgba: "#C19A6B") } 
    static var desertSand: UIColor { return UIColor(rgba: "#EDC9AF") } 
    static var desire: UIColor { return UIColor(rgba: "#EA3C53") } 
    static var diamond: UIColor { return UIColor(rgba: "#B9F2FF") } 
    static var dimGray: UIColor { return UIColor(rgba: "#696969") } 
    static var dingyDungeon: UIColor { return UIColor(rgba: "#C53151") } 
    static var dirt: UIColor { return UIColor(rgba: "#9B7653") } 
    static var dodgerBlue: UIColor { return UIColor(rgba: "#1E90FF") } 
    static var dogwoodRose: UIColor { return UIColor(rgba: "#D71868") } 
    static var dollarBill: UIColor { return UIColor(rgba: "#85BB65") } 
    static var dolphinGray: UIColor { return UIColor(rgba: "#828E84") } 
    static var donkeyBrown: UIColor { return UIColor(rgba: "#664C28") } 
    static var drab: UIColor { return UIColor(rgba: "#967117") } 
    static var dukeBlue: UIColor { return UIColor(rgba: "#00009C") } 
    static var dustStorm: UIColor { return UIColor(rgba: "#E5CCC9") } 
    static var dutchWhite: UIColor { return UIColor(rgba: "#EFDFBB") } 
    static var earthYellow: UIColor { return UIColor(rgba: "#E1A95F") } 
    static var ebony: UIColor { return UIColor(rgba: "#555D50") } 
    static var ecru: UIColor { return UIColor(rgba: "#C2B280") } 
    static var eerieBlack: UIColor { return UIColor(rgba: "#1B1B1B") } 
    static var eggplant: UIColor { return UIColor(rgba: "#614051") } 
    static var eggshell: UIColor { return UIColor(rgba: "#F0EAD6") } 
    static var egyptianBlue: UIColor { return UIColor(rgba: "#1034A6") } 
    static var electricBlue: UIColor { return UIColor(rgba: "#7DF9FF") } 
    static var electricCrimson: UIColor { return UIColor(rgba: "#FF003F") } 
    static var electricCyan: UIColor { return UIColor(rgba: "#00FFFF") } 
    static var electricGreen: UIColor { return UIColor(rgba: "#00FF00") } 
    static var electricIndigo: UIColor { return UIColor(rgba: "#6F00FF") } 
    static var electricLavender: UIColor { return UIColor(rgba: "#F4BBFF") } 
    static var electricLime: UIColor { return UIColor(rgba: "#CCFF00") } 
    static var electricPurple: UIColor { return UIColor(rgba: "#BF00FF") } 
    static var electricUltramarine: UIColor { return UIColor(rgba: "#3F00FF") } 
    static var electricViovar: UIColor { return UIColor(rgba: "#8F00FF") } 
    static var electricYellow: UIColor { return UIColor(rgba: "#FFFF33") } 
    static var emerald: UIColor { return UIColor(rgba: "#50C878") } 
    static var eminence: UIColor { return UIColor(rgba: "#6C3082") } 
    static var englishGreen: UIColor { return UIColor(rgba: "#1B4D3E") } 
    static var englishLavender: UIColor { return UIColor(rgba: "#B48395") } 
    static var englishRed: UIColor { return UIColor(rgba: "#AB4B52") } 
    static var englishVermillion: UIColor { return UIColor(rgba: "#CC474B") } 
    static var englishViovar: UIColor { return UIColor(rgba: "#563C5C") } 
    static var etonBlue: UIColor { return UIColor(rgba: "#96C8A2") } 
    static var eucalyptus: UIColor { return UIColor(rgba: "#44D7A8") } 
    static var fallow: UIColor { return UIColor(rgba: "#C19A6B") } 
    static var faluRed: UIColor { return UIColor(rgba: "#801818") } 
    static var fandango: UIColor { return UIColor(rgba: "#B53389") } 
    static var fandangoPink: UIColor { return UIColor(rgba: "#DE5285") } 
    static var fashionFuchsia: UIColor { return UIColor(rgba: "#F400A1") } 
    static var fawn: UIColor { return UIColor(rgba: "#E5AA70") } 
    static var feldgrau: UIColor { return UIColor(rgba: "#4D5D53") } 
    static var feldspar: UIColor { return UIColor(rgba: "#FDD5B1") } 
    static var fernGreen: UIColor { return UIColor(rgba: "#4F7942") } 
    static var ferrariRed: UIColor { return UIColor(rgba: "#FF2800") } 
    static var fieldDrab: UIColor { return UIColor(rgba: "#6C541E") } 
    static var fieryRose: UIColor { return UIColor(rgba: "#FF5470") } 
    static var firebrick: UIColor { return UIColor(rgba: "#B22222") } 
    static var fireEngineRed: UIColor { return UIColor(rgba: "#CE2029") } 
    static var flame: UIColor { return UIColor(rgba: "#E25822") } 
    static var flamingoPink: UIColor { return UIColor(rgba: "#FC8EAC") } 
    static var flattery: UIColor { return UIColor(rgba: "#6B4423") } 
    static var flavescent: UIColor { return UIColor(rgba: "#F7E98E") } 
    static var flax: UIColor { return UIColor(rgba: "#EEDC82") } 
    static var flirt: UIColor { return UIColor(rgba: "#A2006D") } 
    static var floralWhite: UIColor { return UIColor(rgba: "#FFFAF0") } 
    static var fluorescentOrange: UIColor { return UIColor(rgba: "#FFBF00") } 
    static var fluorescentPink: UIColor { return UIColor(rgba: "#FF1493") } 
    static var fluorescentYellow: UIColor { return UIColor(rgba: "#CCFF00") } 
    static var folly: UIColor { return UIColor(rgba: "#FF004F") } 
    static var forestGreenTraditional: UIColor { return UIColor(rgba: "#014421") } 
    static var forestGreenWeb: UIColor { return UIColor(rgba: "#228B22") } 
    static var frenchBeige: UIColor { return UIColor(rgba: "#A67B5B") } 
    static var frenchBistre: UIColor { return UIColor(rgba: "#856D4D") } 
    static var frenchBlue: UIColor { return UIColor(rgba: "#0072BB") } 
    static var frenchFuchsia: UIColor { return UIColor(rgba: "#FD3F92") } 
    static var frenchLilac: UIColor { return UIColor(rgba: "#86608E") } 
    static var frenchLime: UIColor { return UIColor(rgba: "#9EFD38") } 
    static var frenchMauve: UIColor { return UIColor(rgba: "#D473D4") } 
    static var frenchPink: UIColor { return UIColor(rgba: "#FD6C9E") } 
    static var frenchPlum: UIColor { return UIColor(rgba: "#811453") } 
    static var frenchPuce: UIColor { return UIColor(rgba: "#4E1609") } 
    static var frenchRaspberry: UIColor { return UIColor(rgba: "#C72C48") } 
    static var frenchRose: UIColor { return UIColor(rgba: "#F64A8A") } 
    static var frenchSkyBlue: UIColor { return UIColor(rgba: "#77B5FE") } 
    static var frenchViovar: UIColor { return UIColor(rgba: "#8806CE") } 
    static var frenchWine: UIColor { return UIColor(rgba: "#AC1E44") } 
    static var freshAir: UIColor { return UIColor(rgba: "#A6E7FF") } 
    static var frostbite: UIColor { return UIColor(rgba: "#E936A7") } 
    static var fuchsia: UIColor { return UIColor(rgba: "#FF00FF") } 
    static var fuchsiaCrayola: UIColor { return UIColor(rgba: "#C154C1") } 
    static var fuchsiaPink: UIColor { return UIColor(rgba: "#FF77FF") } 
    static var fuchsiaPurple: UIColor { return UIColor(rgba: "#CC397B") } 
    static var fuchsiaRose: UIColor { return UIColor(rgba: "#C74375") } 
    static var fulvous: UIColor { return UIColor(rgba: "#E48400") } 
    static var fuzzyWuzzy: UIColor { return UIColor(rgba: "#CC6666") } 
    static var gainsboro: UIColor { return UIColor(rgba: "#DCDCDC") } 
    static var gamboge: UIColor { return UIColor(rgba: "#E49B0F") } 
    static var gambogeOrangeBrown: UIColor { return UIColor(rgba: "#996600") } 
    static var gargoyleGas: UIColor { return UIColor(rgba: "#FFDF46") } 
    static var genericViridian: UIColor { return UIColor(rgba: "#007F66") } 
    static var ghostWhite: UIColor { return UIColor(rgba: "#F8F8FF") } 
    static var giantsClub: UIColor { return UIColor(rgba: "#B05C52") } 
    static var giantsOrange: UIColor { return UIColor(rgba: "#FE5A1D") } 
    static var ginger: UIColor { return UIColor(rgba: "#B06500") } 
    static var glaucous: UIColor { return UIColor(rgba: "#6082B6") } 
    static var glitter: UIColor { return UIColor(rgba: "#E6E8FA") } 
    static var glossyGrape: UIColor { return UIColor(rgba: "#AB92B3") } 
    static var gOGreen: UIColor { return UIColor(rgba: "#00AB66") } 
    static var goldMetallic: UIColor { return UIColor(rgba: "#D4AF37") } 
    static var goldWebGolden: UIColor { return UIColor(rgba: "#FFD700") } 
    static var goldFusion: UIColor { return UIColor(rgba: "#85754E") } 
    static var goldenBrown: UIColor { return UIColor(rgba: "#996515") } 
    static var goldenPoppy: UIColor { return UIColor(rgba: "#FCC200") } 
    static var goldenYellow: UIColor { return UIColor(rgba: "#FFDF00") } 
    static var goldenrod: UIColor { return UIColor(rgba: "#DAA520") } 
    static var graniteGray: UIColor { return UIColor(rgba: "#676767") } 
    static var grannySmithApple: UIColor { return UIColor(rgba: "#A8E4A0") } 
    static var grape: UIColor { return UIColor(rgba: "#6F2DA8") } 
    static var gray: UIColor { return UIColor(rgba: "#808080") } 
    static var grayHTMLCSSGray: UIColor { return UIColor(rgba: "#808080") } 
    static var grayX11Gray: UIColor { return UIColor(rgba: "#BEBEBE") } 
    static var grayAsparagus: UIColor { return UIColor(rgba: "#465945") } 
    static var grayBlue: UIColor { return UIColor(rgba: "#8C92AC") } 
    static var greenColorWheelX11Green: UIColor { return UIColor(rgba: "#00FF00") } 
    static var greenCrayola: UIColor { return UIColor(rgba: "#1CAC78") } 
    static var greenHTMLCSSColor: UIColor { return UIColor(rgba: "#008000") } 
    static var greenMunsell: UIColor { return UIColor(rgba: "#00A877") } 
    static var greenNCS: UIColor { return UIColor(rgba: "#009F6B") } 
    static var greenPantone: UIColor { return UIColor(rgba: "#00AD43") } 
    static var greenPigment: UIColor { return UIColor(rgba: "#00A550") } 
    static var greenRYB: UIColor { return UIColor(rgba: "#66B032") } 
    static var greenBlue: UIColor { return UIColor(rgba: "#1164B4") } 
    static var greenCyan: UIColor { return UIColor(rgba: "#009966") } 
    static var greenLizard: UIColor { return UIColor(rgba: "#A7F432") } 
    static var greenSheen: UIColor { return UIColor(rgba: "#6EAEA1") } 
    static var greenYellow: UIColor { return UIColor(rgba: "#ADFF2F") } 
    static var grizzly: UIColor { return UIColor(rgba: "#885818") } 
    static var grullo: UIColor { return UIColor(rgba: "#A99A86") } 
    static var guppieGreen: UIColor { return UIColor(rgba: "#00FF7F") } 
    static var gunmetal: UIColor { return UIColor(rgba: "#2a3439") } 
    static var halayàÚbe: UIColor { return UIColor(rgba: "#663854") } 
    static var hanBlue: UIColor { return UIColor(rgba: "#446CCF") } 
    static var hanPurple: UIColor { return UIColor(rgba: "#5218FA") } 
    static var hansaYellow: UIColor { return UIColor(rgba: "#E9D66B") } 
    static var harlequin: UIColor { return UIColor(rgba: "#3FFF00") } 
    static var harlequinGreen: UIColor { return UIColor(rgba: "#46CB18") } 
    static var harvardCrimson: UIColor { return UIColor(rgba: "#C90016") }
    static var harvestGold: UIColor { return UIColor(rgba: "#DA9100") } 
    static var heartGold: UIColor { return UIColor(rgba: "#808000") } 
    static var heatWave: UIColor { return UIColor(rgba: "#FF7A00") } 
    static var heidelbergRed: UIColor { return UIColor(rgba: "#960018") }
    static var heliotrope: UIColor { return UIColor(rgba: "#DF73FF") } 
    static var heliotropeGray: UIColor { return UIColor(rgba: "#AA98A9") } 
    static var heliotropeMagenta: UIColor { return UIColor(rgba: "#AA00BB") } 
    static var hollywoodCerise: UIColor { return UIColor(rgba: "#F400A1") } 
    static var honeydew: UIColor { return UIColor(rgba: "#F0FFF0") } 
    static var honoluluBlue: UIColor { return UIColor(rgba: "#006DB0") } 
    static var hookersGreen: UIColor { return UIColor(rgba: "#49796B") } 
    static var hotMagenta: UIColor { return UIColor(rgba: "#FF1DCE") } 
    static var hotPink: UIColor { return UIColor(rgba: "#FF69B4") } 
    static var hunterGreen: UIColor { return UIColor(rgba: "#355E3B") } 
    static var iceberg: UIColor { return UIColor(rgba: "#71A6D2") } 
    static var icterine: UIColor { return UIColor(rgba: "#FCF75E") } 
    static var iguanaGreen: UIColor { return UIColor(rgba: "#71BC78") } 
    static var illuminatingEmerald: UIColor { return UIColor(rgba: "#319177") } 
    static var imperial: UIColor { return UIColor(rgba: "#602F6B") } 
    static var imperialBlue: UIColor { return UIColor(rgba: "#002395") } 
    static var imperialPurple: UIColor { return UIColor(rgba: "#66023C") } 
    static var imperialRed: UIColor { return UIColor(rgba: "#ED2939") } 
    static var inchworm: UIColor { return UIColor(rgba: "#B2EC5D") } 
    static var independence: UIColor { return UIColor(rgba: "#4C516D") } 
    static var indiaGreen: UIColor { return UIColor(rgba: "#138808") } 
    static var indianRed: UIColor { return UIColor(rgba: "#CD5C5C") } 
    static var indianYellow: UIColor { return UIColor(rgba: "#E3A857") } 
    static var indigo: UIColor { return UIColor(rgba: "#4B0082") } 
    static var indigoDye: UIColor { return UIColor(rgba: "#091F92") } 
    static var indigoWeb: UIColor { return UIColor(rgba: "#4B0082") } 
    static var infraRed: UIColor { return UIColor(rgba: "#FF496C") } 
    static var interdimensionalBlue: UIColor { return UIColor(rgba: "#360CCC") } 
    static var internationalKleinBlue: UIColor { return UIColor(rgba: "#002FA7") } 
    static var internationalOrangeAerospace: UIColor { return UIColor(rgba: "#FF4F00") } 
    static var internationalOrangeEngineering: UIColor { return UIColor(rgba: "#BA160C") } 
    static var internationalOrangeGoldenGateBridge: UIColor { return UIColor(rgba: "#C0362C") } 
    static var iris: UIColor { return UIColor(rgba: "#5A4FCF") } 
    static var irresistible: UIColor { return UIColor(rgba: "#B3446C") } 
    static var isabelline: UIColor { return UIColor(rgba: "#F4F0EC") } 
    static var islamicGreen: UIColor { return UIColor(rgba: "#009000") } 
    static var italianSkyBlue: UIColor { return UIColor(rgba: "#B2FFFF") } 
    static var ivory: UIColor { return UIColor(rgba: "#FFFFF0") } 
    static var jade: UIColor { return UIColor(rgba: "#00A86B") } 
    static var japaneseCarmine: UIColor { return UIColor(rgba: "#9D2933") } 
    static var japaneseIndigo: UIColor { return UIColor(rgba: "#264348") } 
    static var japaneseViovar: UIColor { return UIColor(rgba: "#5B3256") } 
    static var jasmine: UIColor { return UIColor(rgba: "#F8DE7E") } 
    static var jasper: UIColor { return UIColor(rgba: "#D73B3E") } 
    static var jazzberryJam: UIColor { return UIColor(rgba: "#A50B5E") } 
    static var jellyBean: UIColor { return UIColor(rgba: "#DA614E") } 
    static var jet: UIColor { return UIColor(rgba: "#343434") } 
    static var jonquil: UIColor { return UIColor(rgba: "#F4CA16") } 
    static var jordyBlue: UIColor { return UIColor(rgba: "#8AB9F1") } 
    static var juneBud: UIColor { return UIColor(rgba: "#BDDA57") } 
    static var jungleGreen: UIColor { return UIColor(rgba: "#29AB87") } 
    static var kellyGreen: UIColor { return UIColor(rgba: "#4CBB17") } 
    static var kenyanCopper: UIColor { return UIColor(rgba: "#7C1C05") } 
    static var keppel: UIColor { return UIColor(rgba: "#3AB09E") } 
    static var keyLime: UIColor { return UIColor(rgba: "#E8F48C") } 
    static var khakiHTMLCSSKhaki: UIColor { return UIColor(rgba: "#C3B091") } 
    static var khakiX11LightKhaki: UIColor { return UIColor(rgba: "#F0E68C") } 
    static var kiwi: UIColor { return UIColor(rgba: "#8EE53F") } 
    static var kobe: UIColor { return UIColor(rgba: "#882D17") } 
    static var kobi: UIColor { return UIColor(rgba: "#E79FC4") } 
    static var kobicha: UIColor { return UIColor(rgba: "#6B4423") } 
    static var kombuGreen: UIColor { return UIColor(rgba: "#354230") } 
    static var kSUPurple: UIColor { return UIColor(rgba: "#512888") } 
    static var kUCrimson: UIColor { return UIColor(rgba: "#E8000D") } 
    static var laSalleGreen: UIColor { return UIColor(rgba: "#087830") } 
    static var languidLavender: UIColor { return UIColor(rgba: "#D6CADD") } 
    static var lapisLazuli: UIColor { return UIColor(rgba: "#26619C") } 
    static var laserLemon: UIColor { return UIColor(rgba: "#FFFF66") } 
    static var laurelGreen: UIColor { return UIColor(rgba: "#A9BA9D") } 
    static var lava: UIColor { return UIColor(rgba: "#CF1020") } 
    static var lavenderFloral: UIColor { return UIColor(rgba: "#B57EDC") } 
    static var lavenderWeb: UIColor { return UIColor(rgba: "#E6E6FA") } 
    static var lavenderBlue: UIColor { return UIColor(rgba: "#CCCCFF") } 
    static var lavenderBlush: UIColor { return UIColor(rgba: "#FFF0F5") } 
    static var lavenderGray: UIColor { return UIColor(rgba: "#C4C3D0") } 
    static var lavenderIndigo: UIColor { return UIColor(rgba: "#9457EB") } 
    static var lavenderMagenta: UIColor { return UIColor(rgba: "#EE82EE") } 
    static var lavenderMist: UIColor { return UIColor(rgba: "#E6E6FA") } 
    static var lavenderPink: UIColor { return UIColor(rgba: "#FBAED2") } 
    static var lavenderPurple: UIColor { return UIColor(rgba: "#967BB6") } 
    static var lavenderRose: UIColor { return UIColor(rgba: "#FBA0E3") } 
    static var lawnGreen: UIColor { return UIColor(rgba: "#7CFC00") } 
    static var lemon: UIColor { return UIColor(rgba: "#FFF700") } 
    static var lemonChiffon: UIColor { return UIColor(rgba: "#FFFACD") } 
    static var lemonCurry: UIColor { return UIColor(rgba: "#CCA01D") } 
    static var lemonGlacier: UIColor { return UIColor(rgba: "#FDFF00") } 
    static var lemonLime: UIColor { return UIColor(rgba: "#E3FF00") } 
    static var lemonMeringue: UIColor { return UIColor(rgba: "#F6EABE") } 
    static var lemonYellow: UIColor { return UIColor(rgba: "#FFF44F") } 
    static var licorice: UIColor { return UIColor(rgba: "#1A1110") } 
    static var liberty: UIColor { return UIColor(rgba: "#545AA7") } 
    static var lightApricot: UIColor { return UIColor(rgba: "#FDD5B1") } 
    static var lightBlue: UIColor { return UIColor(rgba: "#ADD8E6") } 
    static var lightBrown: UIColor { return UIColor(rgba: "#B5651D") } 
    static var lightCarminePink: UIColor { return UIColor(rgba: "#E66771") } 
    static var lightCobaltBlue: UIColor { return UIColor(rgba: "#88ACE0") } 
    static var lightCoral: UIColor { return UIColor(rgba: "#F08080") } 
    static var lightCornflowerBlue: UIColor { return UIColor(rgba: "#93CCEA") } 
    static var lightCrimson: UIColor { return UIColor(rgba: "#F56991") } 
    static var lightCyan: UIColor { return UIColor(rgba: "#E0FFFF") } 
    static var lightDeepPink: UIColor { return UIColor(rgba: "#FF5CCD") } 
    static var lightFrenchBeige: UIColor { return UIColor(rgba: "#C8AD7F") } 
    static var lightFuchsiaPink: UIColor { return UIColor(rgba: "#F984EF") } 
    static var lightGoldenrodYellow: UIColor { return UIColor(rgba: "#FAFAD2") } 
    static var lightGray: UIColor { return UIColor(rgba: "#D3D3D3") } 
    static var lightGrayishMagenta: UIColor { return UIColor(rgba: "#CC99CC") } 
    static var lightGreen: UIColor { return UIColor(rgba: "#90EE90") } 
    static var lightHotPink: UIColor { return UIColor(rgba: "#FFB3DE") } 
    static var lightKhaki: UIColor { return UIColor(rgba: "#F0E68C") } 
    static var lightMediumOrchid: UIColor { return UIColor(rgba: "#D39BCB") } 
    static var lightMossGreen: UIColor { return UIColor(rgba: "#ADDFAD") } 
    static var lightOrange: UIColor { return UIColor(rgba: "#FED8B1") } 
    static var lightOrchid: UIColor { return UIColor(rgba: "#E6A8D7") } 
    static var lightPastelPurple: UIColor { return UIColor(rgba: "#B19CD9") } 
    static var lightPink: UIColor { return UIColor(rgba: "#FFB6C1") } 
    static var lightRedOchre: UIColor { return UIColor(rgba: "#E97451") } 
    static var lightSalmon: UIColor { return UIColor(rgba: "#FFA07A") } 
    static var lightSalmonPink: UIColor { return UIColor(rgba: "#FF9999") } 
    static var lightSeaGreen: UIColor { return UIColor(rgba: "#20B2AA") } 
    static var lightSkyBlue: UIColor { return UIColor(rgba: "#87CEFA") } 
    static var lightSlateGray: UIColor { return UIColor(rgba: "#778899") } 
    static var lightSteelBlue: UIColor { return UIColor(rgba: "#B0C4DE") } 
    static var lightTaupe: UIColor { return UIColor(rgba: "#B38B6D") } 
    static var lightThulianPink: UIColor { return UIColor(rgba: "#E68FAC") } 
    static var lightYellow: UIColor { return UIColor(rgba: "#FFFFE0") } 
    static var lilac: UIColor { return UIColor(rgba: "#C8A2C8") } 
    static var lilacLuster: UIColor { return UIColor(rgba: "#AE98AA") } 
    static var limeColorWheel: UIColor { return UIColor(rgba: "#BFFF00") } 
    static var limeWebX11Green: UIColor { return UIColor(rgba: "#00FF00") } 
    static var limeGreen: UIColor { return UIColor(rgba: "#32CD32") } 
    static var limerick: UIColor { return UIColor(rgba: "#9DC209") } 
    static var lincolnGreen: UIColor { return UIColor(rgba: "#195905") } 
    static var linen: UIColor { return UIColor(rgba: "#FAF0E6") } 
    static var loeen: UIColor { return UIColor(rgba: "#15F2FD") }
    static var liseranPurple: UIColor { return UIColor(rgba: "#DE6FA1") } 
    static var littleBoyBlue: UIColor { return UIColor(rgba: "#6CA0DC") } 
    static var liver: UIColor { return UIColor(rgba: "#674C47") } 
    static var liverDogs: UIColor { return UIColor(rgba: "#B86D29") } 
    static var liverOrgan: UIColor { return UIColor(rgba: "#6C2E1F") } 
    static var liverChestnut: UIColor { return UIColor(rgba: "#987456") } 
    static var livid: UIColor { return UIColor(rgba: "#6699CC") } 
    static var lumber: UIColor { return UIColor(rgba: "#FFE4CD") } 
    static var lust: UIColor { return UIColor(rgba: "#E62020") } 
    static var maastrichtBlue: UIColor { return UIColor(rgba: "#001C3D") } 
    static var macaroniAndCheese: UIColor { return UIColor(rgba: "#FFBD88") } 
    static var madderLake: UIColor { return UIColor(rgba: "#CC3336") } 
    static var magenta: UIColor { return UIColor(rgba: "#FF00FF") } 
    static var magentaCrayola: UIColor { return UIColor(rgba: "#FF55A3") } 
    static var magentaDye: UIColor { return UIColor(rgba: "#CA1F7B") } 
    static var magentaPantone: UIColor { return UIColor(rgba: "#D0417E") } 
    static var magentaProcess: UIColor { return UIColor(rgba: "#FF0090") } 
    static var magentaHaze: UIColor { return UIColor(rgba: "#9F4576") } 
    static var magentaPink: UIColor { return UIColor(rgba: "#CC338B") } 
    static var magicMint: UIColor { return UIColor(rgba: "#AAF0D1") } 
    static var magicPotion: UIColor { return UIColor(rgba: "#FF4466") } 
    static var magnolia: UIColor { return UIColor(rgba: "#F8F4FF") } 
    static var mahogany: UIColor { return UIColor(rgba: "#C04000") } 
    static var maize: UIColor { return UIColor(rgba: "#FBEC5D") } 
    static var majorelleBlue: UIColor { return UIColor(rgba: "#6050DC") } 
    static var malachite: UIColor { return UIColor(rgba: "#0BDA51") } 
    static var manatee: UIColor { return UIColor(rgba: "#979AAA") } 
    static var mandarin: UIColor { return UIColor(rgba: "#F37A48") } 
    static var mangoTango: UIColor { return UIColor(rgba: "#FF8243") } 
    static var mantis: UIColor { return UIColor(rgba: "#74C365") } 
    static var mardiGras: UIColor { return UIColor(rgba: "#880085") } 
    static var marigold: UIColor { return UIColor(rgba: "#EAA221") } 
    static var maroonCrayola: UIColor { return UIColor(rgba: "#C32148") } 
    static var maroonHTMLCSS: UIColor { return UIColor(rgba: "#800000") } 
    static var maroonX11: UIColor { return UIColor(rgba: "#B03060") } 
    static var mauve: UIColor { return UIColor(rgba: "#E0B0FF") } 
    static var mauveTaupe: UIColor { return UIColor(rgba: "#915F6D") } 
    static var mauvelous: UIColor { return UIColor(rgba: "#EF98AA") } 
    static var maximumBlue: UIColor { return UIColor(rgba: "#47ABCC") } 
    static var maximumBlueGreen: UIColor { return UIColor(rgba: "#30BFBF") } 
    static var maximumBluePurple: UIColor { return UIColor(rgba: "#ACACE6") } 
    static var maximumGreen: UIColor { return UIColor(rgba: "#5E8C31") } 
    static var maximumGreenYellow: UIColor { return UIColor(rgba: "#D9E650") } 
    static var maximumPurple: UIColor { return UIColor(rgba: "#733380") } 
    static var maximumRed: UIColor { return UIColor(rgba: "#D92121") } 
    static var maximumRedPurple: UIColor { return UIColor(rgba: "#A63A79") } 
    static var maximumYellow: UIColor { return UIColor(rgba: "#FAFA37") } 
    static var maximumYellowRed: UIColor { return UIColor(rgba: "#F2BA49") } 
    static var mayGreen: UIColor { return UIColor(rgba: "#4C9141") } 
    static var mayaBlue: UIColor { return UIColor(rgba: "#73C2FB") } 
    static var meatBrown: UIColor { return UIColor(rgba: "#E5B73B") } 
    static var mediumAquamarine: UIColor { return UIColor(rgba: "#66DDAA") } 
    static var mediumBlue: UIColor { return UIColor(rgba: "#0000CD") } 
    static var mediumCandyAppleRed: UIColor { return UIColor(rgba: "#E2062C") } 
    static var mediumCarmine: UIColor { return UIColor(rgba: "#AF4035") } 
    static var mediumChampagne: UIColor { return UIColor(rgba: "#F3E5AB") } 
    static var mediumElectricBlue: UIColor { return UIColor(rgba: "#035096") } 
    static var mediumJungleGreen: UIColor { return UIColor(rgba: "#1C352D") } 
    static var mediumLavenderMagenta: UIColor { return UIColor(rgba: "#DDA0DD") } 
    static var mediumOrchid: UIColor { return UIColor(rgba: "#BA55D3") } 
    static var mediumPersianBlue: UIColor { return UIColor(rgba: "#0067A5") } 
    static var mediumPurple: UIColor { return UIColor(rgba: "#9370DB") } 
    static var mediumRedViovar: UIColor { return UIColor(rgba: "#BB3385") } 
    static var mediumRuby: UIColor { return UIColor(rgba: "#AA4069") } 
    static var mediumSeaGreen: UIColor { return UIColor(rgba: "#3CB371") } 
    static var mediumSkyBlue: UIColor { return UIColor(rgba: "#80DAEB") } 
    static var mediumSlateBlue: UIColor { return UIColor(rgba: "#7B68EE") } 
    static var mediumSpringBud: UIColor { return UIColor(rgba: "#C9DC87") } 
    static var mediumSpringGreen: UIColor { return UIColor(rgba: "#00FA9A") } 
    static var mediumTaupe: UIColor { return UIColor(rgba: "#674C47") } 
    static var mediumTurquoise: UIColor { return UIColor(rgba: "#48D1CC") } 
    static var mediumTuscanRed: UIColor { return UIColor(rgba: "#79443B") } 
    static var mediumVermilion: UIColor { return UIColor(rgba: "#D9603B") } 
    static var mediumViovarRed: UIColor { return UIColor(rgba: "#C71585") } 
    static var mellowApricot: UIColor { return UIColor(rgba: "#F8B878") } 
    static var mellowYellow: UIColor { return UIColor(rgba: "#F8DE7E") } 
    static var melon: UIColor { return UIColor(rgba: "#FDBCB4") } 
    static var metallicSeaweed: UIColor { return UIColor(rgba: "#0A7E8C") } 
    static var metallicSunburst: UIColor { return UIColor(rgba: "#9C7C38") } 
    static var mexicanPink: UIColor { return UIColor(rgba: "#E4007C") } 
    static var middleBlue: UIColor { return UIColor(rgba: "#7ED4E6") } 
    static var middleBlueGreen: UIColor { return UIColor(rgba: "#8DD9CC") } 
    static var middleBluePurple: UIColor { return UIColor(rgba: "#8B72BE") } 
    static var middleGreen: UIColor { return UIColor(rgba: "#4D8C57") } 
    static var middleGreenYellow: UIColor { return UIColor(rgba: "#ACBF60") } 
    static var middlePurple: UIColor { return UIColor(rgba: "#D982B5") } 
    static var middleRed: UIColor { return UIColor(rgba: "#E58E73") } 
    static var middleRedPurple: UIColor { return UIColor(rgba: "#A55353") } 
    static var middleYellow: UIColor { return UIColor(rgba: "#FFEB00") } 
    static var middleYellowRed: UIColor { return UIColor(rgba: "#ECB176") } 
    static var midnight: UIColor { return UIColor(rgba: "#702670") } 
    static var midnightBlue: UIColor { return UIColor(rgba: "#191970") } 
    static var midnightGreenEagleGreen: UIColor { return UIColor(rgba: "#004953") } 
    static var mikadoYellow: UIColor { return UIColor(rgba: "#FFC40C") } 
    static var milk: UIColor { return UIColor(rgba: "#FDFFF5") } 
    static var mimiPink: UIColor { return UIColor(rgba: "#FFDAE9") } 
    static var mindaro: UIColor { return UIColor(rgba: "#E3F988") } 
    static var ming: UIColor { return UIColor(rgba: "#36747D") } 
    static var minionYellow: UIColor { return UIColor(rgba: "#F5E050") } 
    static var mint: UIColor { return UIColor(rgba: "#3EB489") } 
    static var mintCream: UIColor { return UIColor(rgba: "#F5FFFA") } 
    static var mintGreen: UIColor { return UIColor(rgba: "#98FF98") } 
    static var mistyMoss: UIColor { return UIColor(rgba: "#BBB477") } 
    static var mistyRose: UIColor { return UIColor(rgba: "#FFE4E1") } 
    static var moccasin: UIColor { return UIColor(rgba: "#FAEBD7") } 
    static var modeBeige: UIColor { return UIColor(rgba: "#967117") } 
    static var moonstoneBlue: UIColor { return UIColor(rgba: "#73A9C2") } 
    static var mordantRed19: UIColor { return UIColor(rgba: "#AE0C00") } 
    static var morningBlue: UIColor { return UIColor(rgba: "#8DA399") } 
    static var mossGreen: UIColor { return UIColor(rgba: "#8A9A5B") } 
    static var mountainMeadow: UIColor { return UIColor(rgba: "#30BA8F") } 
    static var mountbattenPink: UIColor { return UIColor(rgba: "#997A8D") } 
    static var mSUGreen: UIColor { return UIColor(rgba: "#18453B") } 
    static var mughalGreen: UIColor { return UIColor(rgba: "#306030") } 
    static var mulberry: UIColor { return UIColor(rgba: "#C54B8C") } 
    static var mummysTomb: UIColor { return UIColor(rgba: "#828E84") } 
    static var mustard: UIColor { return UIColor(rgba: "#FFDB58") } 
    static var myrtleGreen: UIColor { return UIColor(rgba: "#317873") } 
    static var mystic: UIColor { return UIColor(rgba: "#D65282") } 
    static var mysticMaroon: UIColor { return UIColor(rgba: "#AD4379") } 
    static var nadeshikoPink: UIColor { return UIColor(rgba: "#F6ADC6") } 
    static var napierGreen: UIColor { return UIColor(rgba: "#2A8000") } 
    static var naplesYellow: UIColor { return UIColor(rgba: "#FADA5E") } 
    static var navajoWhite: UIColor { return UIColor(rgba: "#FFDEAD") } 
    static var navy: UIColor { return UIColor(rgba: "#000080") } 
    static var navyPurple: UIColor { return UIColor(rgba: "#9457EB") } 
    static var neonCarrot: UIColor { return UIColor(rgba: "#FFA343") } 
    static var neonFuchsia: UIColor { return UIColor(rgba: "#FE4164") } 
    static var neonGreen: UIColor { return UIColor(rgba: "#39FF14") } 
    static var newCar: UIColor { return UIColor(rgba: "#214FC6") } 
    static var newYorkPink: UIColor { return UIColor(rgba: "#D7837F") } 
    static var nickel: UIColor { return UIColor(rgba: "#727472") } 
    static var nonPhotoBlue: UIColor { return UIColor(rgba: "#A4DDED") } 
    static var northTexasGreen: UIColor { return UIColor(rgba: "#059033") } 
    static var nyanza: UIColor { return UIColor(rgba: "#E9FFDB") } 
    static var oceanBlue: UIColor { return UIColor(rgba: "#4F42B5") } 
    static var oceanBoatBlue: UIColor { return UIColor(rgba: "#0077BE") } 
    static var oceanGreen: UIColor { return UIColor(rgba: "#48BF91") } 
    static var ochre: UIColor { return UIColor(rgba: "#CC7722") } 
    static var officeGreen: UIColor { return UIColor(rgba: "#008000") } 
    static var ogreOdor: UIColor { return UIColor(rgba: "#FD5240") } 
    static var oldBurgundy: UIColor { return UIColor(rgba: "#43302E") } 
    static var oldGold: UIColor { return UIColor(rgba: "#CFB53B") } 
    static var oldHeliotrope: UIColor { return UIColor(rgba: "#563C5C") } 
    static var oldLace: UIColor { return UIColor(rgba: "#FDF5E6") } 
    static var oldLavender: UIColor { return UIColor(rgba: "#796878") } 
    static var oldMauve: UIColor { return UIColor(rgba: "#673147") } 
    static var oldMossGreen: UIColor { return UIColor(rgba: "#867E36") } 
    static var oldRose: UIColor { return UIColor(rgba: "#C08081") } 
    static var oldSilver: UIColor { return UIColor(rgba: "#848482") } 
    static var olive: UIColor { return UIColor(rgba: "#808000") } 
    static var oliveDrab3: UIColor { return UIColor(rgba: "#6B8E23") }
    static var oliveDrab7: UIColor { return UIColor(rgba: "#3C341F") }
    static var olivine: UIColor { return UIColor(rgba: "#9AB973") } 
    static var onyx: UIColor { return UIColor(rgba: "#353839") } 
    static var operaMauve: UIColor { return UIColor(rgba: "#B784A7") } 
    static var orangeColorWheel: UIColor { return UIColor(rgba: "#FF7F00") } 
    static var orangeCrayola: UIColor { return UIColor(rgba: "#FF7538") } 
    static var orangePantone: UIColor { return UIColor(rgba: "#FF5800") } 
    static var orangeRYB: UIColor { return UIColor(rgba: "#FB9902") } 
    static var orangeWeb: UIColor { return UIColor(rgba: "#FFA500") } 
    static var orangePeel: UIColor { return UIColor(rgba: "#FF9F00") } 
    static var orangeRed: UIColor { return UIColor(rgba: "#FF4500") } 
    static var orangeSoda: UIColor { return UIColor(rgba: "#FA5B3D") } 
    static var orangeYellow: UIColor { return UIColor(rgba: "#F8D568") } 
    static var orchid: UIColor { return UIColor(rgba: "#DA70D6") } 
    static var orchidPink: UIColor { return UIColor(rgba: "#F2BDCD") } 
    static var oriolesOrange: UIColor { return UIColor(rgba: "#FB4F14") } 
    static var otterBrown: UIColor { return UIColor(rgba: "#654321") } 
    static var outerSpace: UIColor { return UIColor(rgba: "#414A4C") } 
    static var outrageousOrange: UIColor { return UIColor(rgba: "#FF6E4A") } 
    static var oxfordBlue: UIColor { return UIColor(rgba: "#002147") } 
    static var oUCrimsonRed: UIColor { return UIColor(rgba: "#990000") } 
    static var pacificBlue: UIColor { return UIColor(rgba: "#1CA9C9") } 
    static var pakistanGreen: UIColor { return UIColor(rgba: "#006600") } 
    static var palatinateBlue: UIColor { return UIColor(rgba: "#273BE2") } 
    static var palatinatePurple: UIColor { return UIColor(rgba: "#682860") } 
    static var paleAqua: UIColor { return UIColor(rgba: "#BCD4E6") } 
    static var paleBlue: UIColor { return UIColor(rgba: "#AFEEEE") } 
    static var paleBrown: UIColor { return UIColor(rgba: "#987654") } 
    static var paleCarmine: UIColor { return UIColor(rgba: "#AF4035") } 
    static var paleCerulean: UIColor { return UIColor(rgba: "#9BC4E2") } 
    static var paleChestnut: UIColor { return UIColor(rgba: "#DDADAF") } 
    static var paleCopper: UIColor { return UIColor(rgba: "#DA8A67") } 
    static var paleCornflowerBlue: UIColor { return UIColor(rgba: "#ABCDEF") } 
    static var paleCyan: UIColor { return UIColor(rgba: "#87D3F8") } 
    static var paleGold: UIColor { return UIColor(rgba: "#E6BE8A") } 
    static var paleGoldenrod: UIColor { return UIColor(rgba: "#EEE8AA") } 
    static var paleGreen: UIColor { return UIColor(rgba: "#98FB98") } 
    static var paleLavender: UIColor { return UIColor(rgba: "#DCD0FF") } 
    static var paleMagenta: UIColor { return UIColor(rgba: "#F984E5") } 
    static var paleMagentaPink: UIColor { return UIColor(rgba: "#FF99CC") } 
    static var palePink: UIColor { return UIColor(rgba: "#FADADD") } 
    static var palePlum: UIColor { return UIColor(rgba: "#DDA0DD") } 
    static var paleRedViovar: UIColor { return UIColor(rgba: "#DB7093") } 
    static var paleRobinEggBlue: UIColor { return UIColor(rgba: "#96DED1") } 
    static var paleSilver: UIColor { return UIColor(rgba: "#C9C0BB") } 
    static var paleSpringBud: UIColor { return UIColor(rgba: "#ECEBBD") } 
    static var pavaraupe: UIColor { return UIColor(rgba: "#BC987E") } 
    static var pavarurquoise: UIColor { return UIColor(rgba: "#AFEEEE") } 
    static var paleViovar: UIColor { return UIColor(rgba: "#CC99FF") } 
    static var paleViovarRed: UIColor { return UIColor(rgba: "#DB7093") } 
    static var palmLeaf: UIColor { return UIColor(rgba: "#6F9940") } 
    static var pansyPurple: UIColor { return UIColor(rgba: "#78184A") } 
    static var paoloVeroneseGreen: UIColor { return UIColor(rgba: "#009B7D") } 
    static var papayaWhip: UIColor { return UIColor(rgba: "#FFEFD5") } 
    static var paradisePink: UIColor { return UIColor(rgba: "#E63E62") } 
    static var parisGreen: UIColor { return UIColor(rgba: "#50C878") } 
    static var parrotPink: UIColor { return UIColor(rgba: "#D998A0") } 
    static var pastelBlue: UIColor { return UIColor(rgba: "#AEC6CF") } 
    static var pastelBrown: UIColor { return UIColor(rgba: "#836953") } 
    static var pastelGray: UIColor { return UIColor(rgba: "#CFCFC4") } 
    static var pastelGreen: UIColor { return UIColor(rgba: "#77DD77") } 
    static var pastelMagenta: UIColor { return UIColor(rgba: "#F49AC2") } 
    static var pastelOrange: UIColor { return UIColor(rgba: "#FFB347") } 
    static var pastelPink: UIColor { return UIColor(rgba: "#DEA5A4") } 
    static var pastelPurple: UIColor { return UIColor(rgba: "#B39EB5") } 
    static var pastelRed: UIColor { return UIColor(rgba: "#FF6961") } 
    static var pastelViovar: UIColor { return UIColor(rgba: "#CB99C9") } 
    static var pastelYellow: UIColor { return UIColor(rgba: "#FDFD96") } 
    static var patriarch: UIColor { return UIColor(rgba: "#800080") } 
    static var paynesGrey: UIColor { return UIColor(rgba: "#536878") } 
    static var peach: UIColor { return UIColor(rgba: "#FFE5B4") }
    static var peachOrange: UIColor { return UIColor(rgba: "#FFCC99") } 
    static var peachPuff: UIColor { return UIColor(rgba: "#FFDAB9") } 
    static var peachYellow: UIColor { return UIColor(rgba: "#FADFAD") } 
    static var pear: UIColor { return UIColor(rgba: "#D1E231") } 
    static var pearl: UIColor { return UIColor(rgba: "#EAE0C8") } 
    static var pearlAqua: UIColor { return UIColor(rgba: "#88D8C0") } 
    static var pearlyPurple: UIColor { return UIColor(rgba: "#B768A2") } 
    static var peridot: UIColor { return UIColor(rgba: "#E6E200") } 
    static var periwinkle: UIColor { return UIColor(rgba: "#CCCCFF") } 
    static var permanentGeraniumLake: UIColor { return UIColor(rgba: "#E12C2C") } 
    static var persianBlue: UIColor { return UIColor(rgba: "#1C39BB") } 
    static var persianGreen: UIColor { return UIColor(rgba: "#00A693") } 
    static var persianIndigo: UIColor { return UIColor(rgba: "#32127A") } 
    static var persianOrange: UIColor { return UIColor(rgba: "#D99058") } 
    static var persianPink: UIColor { return UIColor(rgba: "#F77FBE") } 
    static var persianPlum: UIColor { return UIColor(rgba: "#701C1C") } 
    static var persianRed: UIColor { return UIColor(rgba: "#CC3333") } 
    static var persianRose: UIColor { return UIColor(rgba: "#FE28A2") } 
    static var persimmon: UIColor { return UIColor(rgba: "#EC5800") } 
    static var peru: UIColor { return UIColor(rgba: "#CD853F") } 
    static var pewterBlue: UIColor { return UIColor(rgba: "#8BA8B7") } 
    static var phlox: UIColor { return UIColor(rgba: "#DF00FF") } 
    static var phthaloBlue: UIColor { return UIColor(rgba: "#000F89") } 
    static var phthaloGreen: UIColor { return UIColor(rgba: "#123524") } 
    static var pictonBlue: UIColor { return UIColor(rgba: "#45B1E8") } 
    static var pictorialCarmine: UIColor { return UIColor(rgba: "#C30B4E") } 
    static var piggyPink: UIColor { return UIColor(rgba: "#FDDDE6") } 
    static var pineGreen: UIColor { return UIColor(rgba: "#01796F") } 
    static var pineapple: UIColor { return UIColor(rgba: "#563C5C") } 
    static var pink: UIColor { return UIColor(rgba: "#FFC0CB") } 
    static var pinkPantone: UIColor { return UIColor(rgba: "#D74894") } 
    static var pinkFlamingo: UIColor { return UIColor(rgba: "#FC74FD") } 
    static var pinkLace: UIColor { return UIColor(rgba: "#FFDDF4") } 
    static var pinkLavender: UIColor { return UIColor(rgba: "#D8B2D1") } 
    static var pinkOrange: UIColor { return UIColor(rgba: "#FF9966") } 
    static var pinkPearl: UIColor { return UIColor(rgba: "#E7ACCF") } 
    static var pinkRaspberry: UIColor { return UIColor(rgba: "#980036") } 
    static var pinkSherbet: UIColor { return UIColor(rgba: "#F78FA7") } 
    static var pistachio: UIColor { return UIColor(rgba: "#93C572") } 
    static var pixiePowder: UIColor { return UIColor(rgba: "#391285") } 
    static var platinum: UIColor { return UIColor(rgba: "#E5E4E2") } 
    static var plum: UIColor { return UIColor(rgba: "#8E4585") } 
    static var plumWeb: UIColor { return UIColor(rgba: "#DDA0DD") } 
    static var plumpPurple: UIColor { return UIColor(rgba: "#5946B2") } 
    static var polishedPine: UIColor { return UIColor(rgba: "#5DA493") } 
    static var pompAndPower: UIColor { return UIColor(rgba: "#86608E") } 
    static var popstar: UIColor { return UIColor(rgba: "#BE4F62") } 
    static var portlandOrange: UIColor { return UIColor(rgba: "#FF5A36") } 
    static var powderBlue: UIColor { return UIColor(rgba: "#B0E0E6") } 
    static var princessPerfume: UIColor { return UIColor(rgba: "#FF85CF") } 
    static var princetonOrange: UIColor { return UIColor(rgba: "#F58025") } 
    static var prune: UIColor { return UIColor(rgba: "#701C1C") } 
    static var prussianBlue: UIColor { return UIColor(rgba: "#003153") } 
    static var psychedelicPurple: UIColor { return UIColor(rgba: "#DF00FF") } 
    static var puce: UIColor { return UIColor(rgba: "#CC8899") } 
    static var puceRed: UIColor { return UIColor(rgba: "#722F37") } 
    static var pullmanBrownUPSBrown: UIColor { return UIColor(rgba: "#644117") } 
    static var pullmanGreen: UIColor { return UIColor(rgba: "#3B331C") } 
    static var pumpkin: UIColor { return UIColor(rgba: "#FF7518") } 
    static var purpleHTML: UIColor { return UIColor(rgba: "#800080") } 
    static var purpleMunsell: UIColor { return UIColor(rgba: "#9F00C5") } 
    static var purpleX11: UIColor { return UIColor(rgba: "#A020F0") } 
    static var purpleHeart: UIColor { return UIColor(rgba: "#69359C") } 
    static var purpleMountainMajesty: UIColor { return UIColor(rgba: "#9678B6") } 
    static var purpleNavy: UIColor { return UIColor(rgba: "#4E5180") } 
    static var purplePizzazz: UIColor { return UIColor(rgba: "#FE4EDA") } 
    static var purplePlum: UIColor { return UIColor(rgba: "#9C51B6") } 
    static var purpvaraupe: UIColor { return UIColor(rgba: "#50404D") } 
    static var purpureus: UIColor { return UIColor(rgba: "#9A4EAE") } 
    static var quartz: UIColor { return UIColor(rgba: "#51484F") } 
    static var queenBlue: UIColor { return UIColor(rgba: "#436B95") } 
    static var queenPink: UIColor { return UIColor(rgba: "#E8CCD7") } 
    static var quickSilver: UIColor { return UIColor(rgba: "#A6A6A6") } 
    static var quinacridoneMagenta: UIColor { return UIColor(rgba: "#8E3A59") } 
    static var rackley: UIColor { return UIColor(rgba: "#5D8AA8") } 
    static var radicalRed: UIColor { return UIColor(rgba: "#FF355E") } 
    static var raisinBlack: UIColor { return UIColor(rgba: "#242124") } 
    static var rajah: UIColor { return UIColor(rgba: "#FBAB60") } 
    static var raspberry: UIColor { return UIColor(rgba: "#E30B5D") } 
    static var raspberryGlace: UIColor { return UIColor(rgba: "#915F6D") } 
    static var raspberryPink: UIColor { return UIColor(rgba: "#E25098") } 
    static var raspberryRose: UIColor { return UIColor(rgba: "#B3446C") } 
    static var rawSienna: UIColor { return UIColor(rgba: "#D68A59") } 
    static var rawUmber: UIColor { return UIColor(rgba: "#826644") } 
    static var razzleDazzleRose: UIColor { return UIColor(rgba: "#FF33CC") } 
    static var razzmatazz: UIColor { return UIColor(rgba: "#E3256B") } 
    static var razzmicBerry: UIColor { return UIColor(rgba: "#8D4E85") } 
    static var rebeccaPurple: UIColor { return UIColor(rgba: "#663399") } 
    static var red: UIColor { return UIColor(rgba: "#FF0000") } 
    static var redCrayola: UIColor { return UIColor(rgba: "#EE204D") } 
    static var redMunsell: UIColor { return UIColor(rgba: "#F2003C") } 
    static var redNCS: UIColor { return UIColor(rgba: "#C40233") } 
    static var redPantone: UIColor { return UIColor(rgba: "#ED2939") } 
    static var redPigment: UIColor { return UIColor(rgba: "#ED1C24") } 
    static var redRYB: UIColor { return UIColor(rgba: "#FE2712") } 
    static var redBrown: UIColor { return UIColor(rgba: "#A52A2A") } 
    static var redDevil: UIColor { return UIColor(rgba: "#860111") } 
    static var redOrange: UIColor { return UIColor(rgba: "#FF5349") } 
    static var redPurple: UIColor { return UIColor(rgba: "#E40078") } 
    static var redSalsa: UIColor { return UIColor(rgba: "#FD3A4A") } 
    static var redViovar: UIColor { return UIColor(rgba: "#C71585") } 
    static var redwood: UIColor { return UIColor(rgba: "#A45A52") } 
    static var regalia: UIColor { return UIColor(rgba: "#522D80") } 
    static var registrationBlack: UIColor { return UIColor(rgba: "#000000") } 
    static var resolutionBlue: UIColor { return UIColor(rgba: "#002387") } 
    static var rhythm: UIColor { return UIColor(rgba: "#777696") } 
    static var richBlack: UIColor { return UIColor(rgba: "#004040") } 
    static var richBlackFOGRA29: UIColor { return UIColor(rgba: "#010B13") } 
    static var richBlackFOGRA39: UIColor { return UIColor(rgba: "#010203") } 
    static var richBrilliantLavender: UIColor { return UIColor(rgba: "#F1A7FE") } 
    static var richCarmine: UIColor { return UIColor(rgba: "#D70040") } 
    static var richElectricBlue: UIColor { return UIColor(rgba: "#0892D0") } 
    static var richLavender: UIColor { return UIColor(rgba: "#A76BCF") } 
    static var richLilac: UIColor { return UIColor(rgba: "#B666D2") } 
    static var richMaroon: UIColor { return UIColor(rgba: "#B03060") } 
    static var rifleGreen: UIColor { return UIColor(rgba: "#444C38") } 
    static var roastCoffee: UIColor { return UIColor(rgba: "#704241") } 
    static var robinEggBlue: UIColor { return UIColor(rgba: "#00CCCC") } 
    static var rocketMetallic: UIColor { return UIColor(rgba: "#8A7F80") } 
    static var romanSilver: UIColor { return UIColor(rgba: "#838996") } 
    static var rose: UIColor { return UIColor(rgba: "#FF007F") } 
    static var roseBonbon: UIColor { return UIColor(rgba: "#F9429E") } 
    static var roseDust: UIColor { return UIColor(rgba: "#9E5E6F") } 
    static var roseEbony: UIColor { return UIColor(rgba: "#674846") } 
    static var roseGold: UIColor { return UIColor(rgba: "#B76E79") } 
    static var roseMadder: UIColor { return UIColor(rgba: "#E32636") } 
    static var rosePink: UIColor { return UIColor(rgba: "#FF66CC") } 
    static var roseQuartz: UIColor { return UIColor(rgba: "#AA98A9") } 
    static var roseRed: UIColor { return UIColor(rgba: "#C21E56") } 
    static var roseTaupe: UIColor { return UIColor(rgba: "#905D5D") } 
    static var roseVale: UIColor { return UIColor(rgba: "#AB4E52") } 
    static var rosewood: UIColor { return UIColor(rgba: "#65000B") } 
    static var rossoCorsa: UIColor { return UIColor(rgba: "#D40000") } 
    static var rosyBrown: UIColor { return UIColor(rgba: "#BC8F8F") } 
    static var royalAzure: UIColor { return UIColor(rgba: "#0038A8") } 
    static var royalBlue: UIColor { return UIColor(rgba: "#002366") }
    static var royalFuchsia: UIColor { return UIColor(rgba: "#CA2C92") } 
    static var royalPurple: UIColor { return UIColor(rgba: "#7851A9") } 
    static var royalYellow: UIColor { return UIColor(rgba: "#FADA5E") } 
    static var ruber: UIColor { return UIColor(rgba: "#CE4676") } 
    static var rubineRed: UIColor { return UIColor(rgba: "#D10056") } 
    static var ruby: UIColor { return UIColor(rgba: "#E0115F") } 
    static var rubyRed: UIColor { return UIColor(rgba: "#9B111E") } 
    static var ruddy: UIColor { return UIColor(rgba: "#FF0028") } 
    static var ruddyBrown: UIColor { return UIColor(rgba: "#BB6528") } 
    static var ruddyPink: UIColor { return UIColor(rgba: "#E18E96") } 
    static var rufous: UIColor { return UIColor(rgba: "#A81C07") } 
    static var russet: UIColor { return UIColor(rgba: "#80461B") } 
    static var russianGreen: UIColor { return UIColor(rgba: "#679267") } 
    static var russianViovar: UIColor { return UIColor(rgba: "#32174D") } 
    static var rust: UIColor { return UIColor(rgba: "#B7410E") } 
    static var rustyRed: UIColor { return UIColor(rgba: "#DA2C43") } 
    static var sacramentoStateGreen: UIColor { return UIColor(rgba: "#00563F") } 
    static var saddleBrown: UIColor { return UIColor(rgba: "#8B4513") } 
    static var safetyOrange: UIColor { return UIColor(rgba: "#FF7800") } 
    static var safetyOrangeBlazeOrange: UIColor { return UIColor(rgba: "#FF6700") } 
    static var safetyYellow: UIColor { return UIColor(rgba: "#EED202") } 
    static var saffron: UIColor { return UIColor(rgba: "#F4C430") } 
    static var sage: UIColor { return UIColor(rgba: "#BCB88A") } 
    static var stPatricksBlue: UIColor { return UIColor(rgba: "#23297A") }
    static var salmon: UIColor { return UIColor(rgba: "#FA8072") } 
    static var salmonPink: UIColor { return UIColor(rgba: "#FF91A4") } 
    static var sand: UIColor { return UIColor(rgba: "#C2B280") } 
    static var sandDune: UIColor { return UIColor(rgba: "#967117") } 
    static var sandstorm: UIColor { return UIColor(rgba: "#ECD540") } 
    static var sandyBrown: UIColor { return UIColor(rgba: "#F4A460") } 
    static var sandyTan: UIColor { return UIColor(rgba: "#FDD9B5") } 
    static var sandyTaupe: UIColor { return UIColor(rgba: "#967117") } 
    static var sangria: UIColor { return UIColor(rgba: "#92000A") } 
    static var sapGreen: UIColor { return UIColor(rgba: "#507D2A") } 
    static var sapphire: UIColor { return UIColor(rgba: "#0F52BA") } 
    static var sapphireBlue: UIColor { return UIColor(rgba: "#0067A5") } 
    static var sasquatchSocks: UIColor { return UIColor(rgba: "#FF4681") } 
    static var satinSheenGold: UIColor { return UIColor(rgba: "#CBA135") } 
    static var scarvar: UIColor { return UIColor(rgba: "#FF2400") }
    static var schaussPink: UIColor { return UIColor(rgba: "#FF91AF") } 
    static var schoolBusYellow: UIColor { return UIColor(rgba: "#FFD800") } 
    static var screaminGreen: UIColor { return UIColor(rgba: "#66FF66") } 
    static var seaBlue: UIColor { return UIColor(rgba: "#006994") } 
    static var seaFoamGreen: UIColor { return UIColor(rgba: "#9FE2BF") } 
    static var seaGreen: UIColor { return UIColor(rgba: "#2E8B57") } 
    static var seaSerpent: UIColor { return UIColor(rgba: "#4BC7CF") } 
    static var sealBrown: UIColor { return UIColor(rgba: "#59260B") } 
    static var seashell: UIColor { return UIColor(rgba: "#FFF5EE") } 
    static var selectiveYellow: UIColor { return UIColor(rgba: "#FFBA00") } 
    static var sepia: UIColor { return UIColor(rgba: "#704214") } 
    static var shadow: UIColor { return UIColor(rgba: "#8A795D") } 
    static var shadowBlue: UIColor { return UIColor(rgba: "#778BA5") } 
    static var shampoo: UIColor { return UIColor(rgba: "#FFCFF1") } 
    static var shamrockGreen: UIColor { return UIColor(rgba: "#009E60") } 
    static var sheenGreen: UIColor { return UIColor(rgba: "#8FD400") } 
    static var shimmeringBlush: UIColor { return UIColor(rgba: "#D98695") } 
    static var shinyShamrock: UIColor { return UIColor(rgba: "#5FA778") } 
    static var shockingPink: UIColor { return UIColor(rgba: "#FC0FC0") } 
    static var shockingPinkCrayola: UIColor { return UIColor(rgba: "#FF6FFF") } 
    static var sienna: UIColor { return UIColor(rgba: "#882D17") } 
    static var silver: UIColor { return UIColor(rgba: "#C0C0C0") } 
    static var silverChalice: UIColor { return UIColor(rgba: "#ACACAC") } 
    static var silverLakeBlue: UIColor { return UIColor(rgba: "#5D89BA") } 
    static var silverPink: UIColor { return UIColor(rgba: "#C4AEAD") } 
    static var silverSand: UIColor { return UIColor(rgba: "#BFC1C2") } 
    static var sinopia: UIColor { return UIColor(rgba: "#CB410B") } 
    static var sizzlingRed: UIColor { return UIColor(rgba: "#FF3855") } 
    static var sizzlingSunrise: UIColor { return UIColor(rgba: "#FFDB00") } 
    static var skobeloff: UIColor { return UIColor(rgba: "#007474") } 
    static var skyBlue: UIColor { return UIColor(rgba: "#87CEEB") } 
    static var skyMagenta: UIColor { return UIColor(rgba: "#CF71AF") } 
    static var slateBlue: UIColor { return UIColor(rgba: "#6A5ACD") } 
    static var slateGray: UIColor { return UIColor(rgba: "#708090") } 
    static var smaltDarkPowderBlue: UIColor { return UIColor(rgba: "#003399") } 
    static var slimyGreen: UIColor { return UIColor(rgba: "#299617") } 
    static var smashedPumpkin: UIColor { return UIColor(rgba: "#FF6D3A") } 
    static var smitten: UIColor { return UIColor(rgba: "#C84186") } 
    static var smoke: UIColor { return UIColor(rgba: "#738276") } 
    static var smokeyTopaz: UIColor { return UIColor(rgba: "#832A0D") } 
    static var smokyBlack: UIColor { return UIColor(rgba: "#100C08") } 
    static var smokyTopaz: UIColor { return UIColor(rgba: "#933D41") } 
    static var snow: UIColor { return UIColor(rgba: "#FFFAFA") } 
    static var soap: UIColor { return UIColor(rgba: "#CEC8EF") } 
    static var solidPink: UIColor { return UIColor(rgba: "#893843") } 
    static var sonicSilver: UIColor { return UIColor(rgba: "#757575") } 
    static var spartanCrimson: UIColor { return UIColor(rgba: "#9E1316") } 
    static var spaceCadet: UIColor { return UIColor(rgba: "#1D2951") } 
    static var spanishBistre: UIColor { return UIColor(rgba: "#807532") } 
    static var spanishBlue: UIColor { return UIColor(rgba: "#0070B8") } 
    static var spanishCarmine: UIColor { return UIColor(rgba: "#D10047") } 
    static var spanishCrimson: UIColor { return UIColor(rgba: "#E51A4C") } 
    static var spanishGray: UIColor { return UIColor(rgba: "#989898") } 
    static var spanishGreen: UIColor { return UIColor(rgba: "#009150") } 
    static var spanishOrange: UIColor { return UIColor(rgba: "#E86100") } 
    static var spanishPink: UIColor { return UIColor(rgba: "#F7BFBE") } 
    static var spanishRed: UIColor { return UIColor(rgba: "#E60026") } 
    static var spanishSkyBlue: UIColor { return UIColor(rgba: "#00FFFF") } 
    static var spanishViovar: UIColor { return UIColor(rgba: "#4C2882") } 
    static var spanishViridian: UIColor { return UIColor(rgba: "#007F5C") } 
    static var spicyMix: UIColor { return UIColor(rgba: "#8B5f4D") } 
    static var spiroDiscoBall: UIColor { return UIColor(rgba: "#0FC0FC") } 
    static var springBud: UIColor { return UIColor(rgba: "#A7FC00") } 
    static var springFrost: UIColor { return UIColor(rgba: "#87FF2A") } 
    static var springGreen: UIColor { return UIColor(rgba: "#00FF7F") } 
    static var starCommandBlue: UIColor { return UIColor(rgba: "#007BB8") } 
    static var steelBlue: UIColor { return UIColor(rgba: "#4682B4") } 
    static var steelPink: UIColor { return UIColor(rgba: "#CC33CC") } 
    static var steelTeal: UIColor { return UIColor(rgba: "#5F8A8B") } 
    static var stilDeGrainYellow: UIColor { return UIColor(rgba: "#FADA5E") } 
    static var stizza: UIColor { return UIColor(rgba: "#990000") } 
    static var stormcloud: UIColor { return UIColor(rgba: "#4F666A") } 
    static var straw: UIColor { return UIColor(rgba: "#E4D96F") } 
    static var strawberry: UIColor { return UIColor(rgba: "#FC5A8D") } 
    static var sugarPlum: UIColor { return UIColor(rgba: "#914E75") } 
    static var sunburntCyclops: UIColor { return UIColor(rgba: "#FF404C") } 
    static var sunglow: UIColor { return UIColor(rgba: "#FFCC33") } 
    static var sunny: UIColor { return UIColor(rgba: "#F2F27A") } 
    static var sunray: UIColor { return UIColor(rgba: "#E3AB57") } 
    static var sunset: UIColor { return UIColor(rgba: "#FAD6A5") } 
    static var sunsetOrange: UIColor { return UIColor(rgba: "#FD5E53") } 
    static var superPink: UIColor { return UIColor(rgba: "#CF6BA9") } 
    static var sweetBrown: UIColor { return UIColor(rgba: "#A83731") } 
    static var tan: UIColor { return UIColor(rgba: "#D2B48C") } 
    static var tangelo: UIColor { return UIColor(rgba: "#F94D00") } 
    static var tangerine: UIColor { return UIColor(rgba: "#F28500") } 
    static var tangerineYellow: UIColor { return UIColor(rgba: "#FFCC00") } 
    static var tangoPink: UIColor { return UIColor(rgba: "#E4717A") } 
    static var tartOrange: UIColor { return UIColor(rgba: "#FB4D46") } 
    static var taupe: UIColor { return UIColor(rgba: "#483C32") } 
    static var taupeGray: UIColor { return UIColor(rgba: "#8B8589") } 
    static var teaGreen: UIColor { return UIColor(rgba: "#D0F0C0") } 
    static var teaRose: UIColor { return UIColor(rgba: "#F88379") }
    static var teal: UIColor { return UIColor(rgba: "#008080") } 
    static var tealBlue: UIColor { return UIColor(rgba: "#367588") } 
    static var tealDeer: UIColor { return UIColor(rgba: "#99E6B3") } 
    static var tealGreen: UIColor { return UIColor(rgba: "#00827F") } 
    static var telemagenta: UIColor { return UIColor(rgba: "#CF3476") } 
    static var tenneTawny: UIColor { return UIColor(rgba: "#CD5700") }
    static var terraCotta: UIColor { return UIColor(rgba: "#E2725B") } 
    static var thistle: UIColor { return UIColor(rgba: "#D8BFD8") } 
    static var thulianPink: UIColor { return UIColor(rgba: "#DE6FA1") } 
    static var tickleMePink: UIColor { return UIColor(rgba: "#FC89AC") } 
    static var tiffanyBlue: UIColor { return UIColor(rgba: "#0ABAB5") } 
    static var tigersEye: UIColor { return UIColor(rgba: "#E08D3C") } 
    static var timberwolf: UIColor { return UIColor(rgba: "#DBD7D2") } 
    static var titaniumYellow: UIColor { return UIColor(rgba: "#EEE600") } 
    static var tomato: UIColor { return UIColor(rgba: "#FF6347") } 
    static var toolbox: UIColor { return UIColor(rgba: "#746CC0") } 
    static var topaz: UIColor { return UIColor(rgba: "#FFC87C") } 
    static var tractorRed: UIColor { return UIColor(rgba: "#FD0E35") } 
    static var trolleyGrey: UIColor { return UIColor(rgba: "#808080") } 
    static var tropicalRainForest: UIColor { return UIColor(rgba: "#00755E") } 
    static var tropicalViovar: UIColor { return UIColor(rgba: "#CDA4DE") } 
    static var trueBlue: UIColor { return UIColor(rgba: "#0073CF") } 
    static var tuftsBlue: UIColor { return UIColor(rgba: "#3E8EDE") } 
    static var tulip: UIColor { return UIColor(rgba: "#FF878D") } 
    static var tumbleweed: UIColor { return UIColor(rgba: "#DEAA88") } 
    static var turkishRose: UIColor { return UIColor(rgba: "#B57281") } 
    static var turquoise: UIColor { return UIColor(rgba: "#40E0D0") } 
    static var turquoiseBlue: UIColor { return UIColor(rgba: "#00FFEF") } 
    static var turquoiseGreen: UIColor { return UIColor(rgba: "#A0D6B4") } 
    static var turquoiseSurf: UIColor { return UIColor(rgba: "#00C5CD") } 
    static var turtleGreen: UIColor { return UIColor(rgba: "#8A9A5B") } 
    static var tuscan: UIColor { return UIColor(rgba: "#FAD6A5") } 
    static var tuscanBrown: UIColor { return UIColor(rgba: "#6F4E37") } 
    static var tuscanRed: UIColor { return UIColor(rgba: "#7C4848") } 
    static var tuscanTan: UIColor { return UIColor(rgba: "#A67B5B") } 
    static var tuscany: UIColor { return UIColor(rgba: "#C09999") } 
    static var twilightLavender: UIColor { return UIColor(rgba: "#8A496B") } 
    static var tyrianPurple: UIColor { return UIColor(rgba: "#66023C") } 
    static var uABlue: UIColor { return UIColor(rgba: "#0033AA") } 
    static var uARed: UIColor { return UIColor(rgba: "#D9004C") } 
    static var ube: UIColor { return UIColor(rgba: "#8878C3") } 
    static var uCLABlue: UIColor { return UIColor(rgba: "#536895") } 
    static var uCLAGold: UIColor { return UIColor(rgba: "#FFB300") } 
    static var uFOGreen: UIColor { return UIColor(rgba: "#3CD070") } 
    static var ultramarine: UIColor { return UIColor(rgba: "#3F00FF") } 
    static var ultramarineBlue: UIColor { return UIColor(rgba: "#4166F5") } 
    static var ultraPink: UIColor { return UIColor(rgba: "#FF6FFF") } 
    static var ultraRed: UIColor { return UIColor(rgba: "#FC6C85") } 
    static var umber: UIColor { return UIColor(rgba: "#635147") } 
    static var unbleachedSilk: UIColor { return UIColor(rgba: "#FFDDCA") } 
    static var unitedNationsBlue: UIColor { return UIColor(rgba: "#5B92E5") } 
    static var universityOfCaliforniaGold: UIColor { return UIColor(rgba: "#B78727") } 
    static var unmellowYellow: UIColor { return UIColor(rgba: "#FFFF66") } 
    static var uPForestGreen: UIColor { return UIColor(rgba: "#014421") } 
    static var uPMaroon: UIColor { return UIColor(rgba: "#7B1113") } 
    static var upsdellRed: UIColor { return UIColor(rgba: "#AE2029") } 
    static var urobilin: UIColor { return UIColor(rgba: "#E1AD21") } 
    static var uSAFABlue: UIColor { return UIColor(rgba: "#004F98") } 
    static var uSCCardinal: UIColor { return UIColor(rgba: "#990000") } 
    static var uSCGold: UIColor { return UIColor(rgba: "#FFCC00") } 
    static var universityOfTennesseeOrange: UIColor { return UIColor(rgba: "#F77F00") } 
    static var utahCrimson: UIColor { return UIColor(rgba: "#D3003F") } 
    static var vanDykeBrown: UIColor { return UIColor(rgba: "#664228") } 
    static var vanilla: UIColor { return UIColor(rgba: "#F3E5AB") } 
    static var vanillaIce: UIColor { return UIColor(rgba: "#F38FA9") } 
    static var vegasGold: UIColor { return UIColor(rgba: "#C5B358") } 
    static var venetianRed: UIColor { return UIColor(rgba: "#C80815") } 
    static var verdigris: UIColor { return UIColor(rgba: "#43B3AE") } 
    static var vermilion: UIColor { return UIColor(rgba: "#E34234") } 
    static var veronica: UIColor { return UIColor(rgba: "#A020F0") } 
    static var veryLightAzure: UIColor { return UIColor(rgba: "#74BBFB") } 
    static var veryLightBlue: UIColor { return UIColor(rgba: "#6666FF") } 
    static var veryLightMalachiteGreen: UIColor { return UIColor(rgba: "#64E986") } 
    static var veryLightTangelo: UIColor { return UIColor(rgba: "#FFB077") } 
    static var veryPaleOrange: UIColor { return UIColor(rgba: "#FFDFBF") } 
    static var veryPaleYellow: UIColor { return UIColor(rgba: "#FFFFBF") } 
    static var viovar: UIColor { return UIColor(rgba: "#8F00FF") } 
    static var viovarColorWheel: UIColor { return UIColor(rgba: "#7F00FF") } 
    static var viovarRYB: UIColor { return UIColor(rgba: "#8601AF") } 
    static var viovarWeb: UIColor { return UIColor(rgba: "#EE82EE") } 
    static var viovarBlue: UIColor { return UIColor(rgba: "#324AB2") } 
    static var viovarRed: UIColor { return UIColor(rgba: "#F75394") } 
    static var viridian: UIColor { return UIColor(rgba: "#40826D") } 
    static var viridianGreen: UIColor { return UIColor(rgba: "#009698") } 
    static var vistaBlue: UIColor { return UIColor(rgba: "#7C9ED9") } 
    static var vividAmber: UIColor { return UIColor(rgba: "#CC9900") } 
    static var vividAuburn: UIColor { return UIColor(rgba: "#922724") } 
    static var vividBurgundy: UIColor { return UIColor(rgba: "#9F1D35") } 
    static var vividCerise: UIColor { return UIColor(rgba: "#DA1D81") } 
    static var vividCerulean: UIColor { return UIColor(rgba: "#00AAEE") } 
    static var vividCrimson: UIColor { return UIColor(rgba: "#CC0033") } 
    static var vividGamboge: UIColor { return UIColor(rgba: "#FF9900") } 
    static var vividLimeGreen: UIColor { return UIColor(rgba: "#A6D608") } 
    static var vividMalachite: UIColor { return UIColor(rgba: "#00CC33") } 
    static var vividMulberry: UIColor { return UIColor(rgba: "#B80CE3") } 
    static var vividOrange: UIColor { return UIColor(rgba: "#FF5F00") } 
    static var vividOrangePeel: UIColor { return UIColor(rgba: "#FFA000") } 
    static var vividOrchid: UIColor { return UIColor(rgba: "#CC00FF") } 
    static var vividRaspberry: UIColor { return UIColor(rgba: "#FF006C") } 
    static var vividRed: UIColor { return UIColor(rgba: "#F70D1A") } 
    static var vividRedTangelo: UIColor { return UIColor(rgba: "#DF6124") } 
    static var vividSkyBlue: UIColor { return UIColor(rgba: "#00CCFF") } 
    static var vividTangelo: UIColor { return UIColor(rgba: "#F07427") } 
    static var vividTangerine: UIColor { return UIColor(rgba: "#FFA089") } 
    static var vividVermilion: UIColor { return UIColor(rgba: "#E56024") } 
    static var vividViovar: UIColor { return UIColor(rgba: "#9F00FF") } 
    static var vividYellow: UIColor { return UIColor(rgba: "#FFE302") } 
    static var volt: UIColor { return UIColor(rgba: "#CEFF00") } 
    static var wageningenGreen: UIColor { return UIColor(rgba: "#34B233") } 
    static var warmBlack: UIColor { return UIColor(rgba: "#004242") } 
    static var waterspout: UIColor { return UIColor(rgba: "#A4F4F9") } 
    static var weldonBlue: UIColor { return UIColor(rgba: "#7C98AB") } 
    static var wenge: UIColor { return UIColor(rgba: "#645452") } 
    static var wheat: UIColor { return UIColor(rgba: "#F5DEB3") } 
    static var white: UIColor { return UIColor(rgba: "#FFFFFF") } 
    static var whiteSmoke: UIColor { return UIColor(rgba: "#F5F5F5") } 
    static var wildBlueYonder: UIColor { return UIColor(rgba: "#A2ADD0") } 
    static var wildOrchid: UIColor { return UIColor(rgba: "#D470A2") } 
    static var wildStrawberry: UIColor { return UIColor(rgba: "#FF43A4") } 
    static var wildWatermelon: UIColor { return UIColor(rgba: "#FC6C85") } 
    static var willpowerOrange: UIColor { return UIColor(rgba: "#FD5800") } 
    static var windsorTan: UIColor { return UIColor(rgba: "#A75502") } 
    static var wine: UIColor { return UIColor(rgba: "#722F37") } 
    static var wineDregs: UIColor { return UIColor(rgba: "#673147") } 
    static var winterSky: UIColor { return UIColor(rgba: "#FF007C") } 
    static var winterWizard: UIColor { return UIColor(rgba: "#A0E6FF") } 
    static var wintergreenDream: UIColor { return UIColor(rgba: "#56887D") } 
    static var wisteria: UIColor { return UIColor(rgba: "#C9A0DC") } 
    static var woodBrown: UIColor { return UIColor(rgba: "#C19A6B") } 
    static var xanadu: UIColor { return UIColor(rgba: "#738678") } 
    static var yaleBlue: UIColor { return UIColor(rgba: "#0F4D92") } 
    static var yankeesBlue: UIColor { return UIColor(rgba: "#1C2841") } 
    static var yellow: UIColor { return UIColor(rgba: "#FFFF00") } 
    static var yellowCrayola: UIColor { return UIColor(rgba: "#FCE883") } 
    static var yellowMunsell: UIColor { return UIColor(rgba: "#EFCC00") } 
    static var yellowNCS: UIColor { return UIColor(rgba: "#FFD300") } 
    static var yellowPantone: UIColor { return UIColor(rgba: "#FEDF00") } 
    static var yellowProcess: UIColor { return UIColor(rgba: "#FFEF00") } 
    static var yellowRYB: UIColor { return UIColor(rgba: "#FEFE33") } 
    static var yellowGreen: UIColor { return UIColor(rgba: "#9ACD32") } 
    static var yellowOrange: UIColor { return UIColor(rgba: "#FFAE42") } 
    static var yellowRose: UIColor { return UIColor(rgba: "#FFF000") } 
    static var yellowSunshine: UIColor { return UIColor(rgba: "#FFF700") } 
    static var zaffre: UIColor { return UIColor(rgba: "#0014A8") } 
    static var zinnwalditeBrown: UIColor { return UIColor(rgba: "#2C1608") } 
    static var zomp: UIColor { return UIColor(rgba: "#39A78E") }  
}
